#include <TStyle.h>
#include <TCanvas.h>
#include <TLorentzVector.h>
#include <TSystem.h>
#include <TROOT.h>
#include <TH1.h>
#include <TH2.h>
#include <TFile.h>
#include <TCanvas.h>
#include <TSpline.h>
#include <math.h>
#include <TH1F.h>
#include <THStack.h>

#define PI 3.14159265358979323846

#include <iostream>
#include <vector>
#include <set>
using namespace std;

int CompHistos()
{
		  gStyle->SetOptStat(0);

		  //char* const hist[] = {"mumu_mass", "mumu_pt", "mumu_y", "xi_left", "xi_right"}; 

		  //size_t Nhist = sizeof(hist)/sizeof(hist[0]);

		  TFile *f_elastic_x130 = new TFile("histos_MC/output_elastic_xangle130_cut.root");
		  TFile *f_inel_el_x130 = new TFile("histos_MC/output_inel-el_xangle130_cut.root");
		  TFile *f_dy = new TFile("histos_MC/output_dy_cut.root");
		  TFile *f_dy_resample = new TFile("histos_MC/output_dy_resample.root");
		  TFile *f_data = new TFile("histos_data/output_data_cut.root");

		  //for (int i = 0; i < Nhist; i++) {

		  double scale_factor_elastic_x120, scale_factor_elastic_x130, scale_factor_elastic_x140, scale_factor_elastic_x150;
		  double scale_factor_inel_el_x120, scale_factor_inel_el_x130, scale_factor_inel_el_x140, scale_factor_inel_el_x150;
		  double scale_factor_dy, scale_factor_dy_resample;
		  double eff_trigger_elastic_x130 = 1; //178402/200000
		  double eff_trigger_inel_el_x130 = 1; //178174/200000
		  double event_selection = 1; //18964806/23701056
		  double eff_trigger_dy = 1; //7137203/48675378
		  double resample_ratio = 1;

		  TH1* h_elastic_x130_mass = 0;
		  TH1* h_inel_el_x130_mass = 0;
		  TH1* h_dy_mass = 0;
		  TH1* h_dy_resample_mass = 0;
		  TH1* h_data_mass = 0;
		  TH1* h_elastic_x130_pt = 0;
		  TH1* h_inel_el_x130_pt = 0;
		  TH1* h_dy_pt = 0;
		  TH1* h_dy_resample_pt = 0;
		  TH1* h_data_pt = 0;
		  TH1* h_elastic_x130_y = 0;
		  TH1* h_inel_el_x130_y = 0;
		  TH1* h_dy_y = 0;
		  TH1* h_dy_resample_y = 0;
		  TH1* h_data_y = 0;
		  TH1* h_elastic_x130_proton_xi_left_single = 0;
		  TH1* h_inel_el_x130_proton_xi_left_single = 0;
		  TH1* h_dy_proton_xi_left_single = 0;
		  TH1* h_dy_resample_proton_xi_left_single = 0;
		  TH1* h_data_proton_xi_left_single = 0;
		  TH1* h_elastic_x130_proton_xi_right_single = 0;
		  TH1* h_inel_el_x130_proton_xi_right_single = 0;
		  TH1* h_dy_proton_xi_right_single = 0;
		  TH1* h_dy_resample_proton_xi_right_single = 0;
		  TH1* h_data_proton_xi_right_single = 0;
		  TH1* h_elastic_x130_proton_xi_left_multi = 0;
		  TH1* h_inel_el_x130_proton_xi_left_multi = 0;
		  TH1* h_dy_proton_xi_left_multi = 0;
		  TH1* h_dy_resample_proton_xi_left_multi = 0;
		  TH1* h_data_proton_xi_left_multi = 0;
		  TH1* h_elastic_x130_proton_xi_right_multi = 0;
		  TH1* h_inel_el_x130_proton_xi_right_multi = 0;
		  TH1* h_dy_proton_xi_right_multi = 0;
		  TH1* h_dy_resample_proton_xi_right_multi = 0;
		  TH1* h_data_proton_xi_right_multi = 0;
		  TH1* h_elastic_x130_diff_proton_reco_pair_xi_left_single = 0;
		  TH1* h_inel_el_x130_diff_proton_reco_pair_xi_left_single = 0;
		  TH1* h_dy_diff_proton_reco_pair_xi_left_single = 0;
		  TH1* h_dy_resample_diff_proton_reco_pair_xi_left_single = 0;
		  TH1* h_data_diff_proton_reco_pair_xi_left_single = 0;
		  TH1* h_elastic_x130_diff_proton_reco_pair_xi_right_single = 0;
		  TH1* h_inel_el_x130_diff_proton_reco_pair_xi_right_single = 0;
		  TH1* h_dy_diff_proton_reco_pair_xi_right_single = 0;
		  TH1* h_dy_resample_diff_proton_reco_pair_xi_right_single = 0;
		  TH1* h_data_diff_proton_reco_pair_xi_right_single = 0;
		  TH1* h_elastic_x130_diff_proton_reco_pair_xi_left_multi = 0;
		  TH1* h_inel_el_x130_diff_proton_reco_pair_xi_left_multi = 0;
		  TH1* h_dy_diff_proton_reco_pair_xi_left_multi = 0;
		  TH1* h_dy_resample_diff_proton_reco_pair_xi_left_multi = 0;
		  TH1* h_data_diff_proton_reco_pair_xi_left_multi = 0;
		  TH1* h_elastic_x130_diff_proton_reco_pair_xi_right_multi = 0;
		  TH1* h_inel_el_x130_diff_proton_reco_pair_xi_right_multi = 0;
		  TH1* h_dy_diff_proton_reco_pair_xi_right_multi = 0;
		  TH1* h_dy_resample_diff_proton_reco_pair_xi_right_multi = 0;
		  TH1* h_data_diff_proton_reco_pair_xi_right_multi = 0;
		  TH1* h_elastic_x130_ratio_proton_reco_pair_xi_left_single = 0;
		  TH1* h_inel_el_x130_ratio_proton_reco_pair_xi_left_single = 0;
		  TH1* h_dy_ratio_proton_reco_pair_xi_left_single = 0;
		  TH1* h_dy_resample_ratio_proton_reco_pair_xi_left_single = 0;
		  TH1* h_data_ratio_proton_reco_pair_xi_left_single = 0;
		  TH1* h_elastic_x130_ratio_proton_reco_pair_xi_right_single = 0;
		  TH1* h_inel_el_x130_ratio_proton_reco_pair_xi_right_single = 0;
		  TH1* h_dy_ratio_proton_reco_pair_xi_right_single = 0;
		  TH1* h_dy_resample_ratio_proton_reco_pair_xi_right_single = 0;
		  TH1* h_data_ratio_proton_reco_pair_xi_right_single = 0;
		  TH1* h_elastic_x130_ratio_proton_reco_pair_xi_left_multi = 0;
		  TH1* h_inel_el_x130_ratio_proton_reco_pair_xi_left_multi = 0;
		  TH1* h_dy_ratio_proton_reco_pair_xi_left_multi = 0;
		  TH1* h_dy_resample_ratio_proton_reco_pair_xi_left_multi = 0;
		  TH1* h_data_ratio_proton_reco_pair_xi_left_multi = 0;
		  TH1* h_elastic_x130_ratio_proton_reco_pair_xi_right_multi = 0;
		  TH1* h_inel_el_x130_ratio_proton_reco_pair_xi_right_multi = 0;
		  TH1* h_dy_ratio_proton_reco_pair_xi_right_multi = 0;
		  TH1* h_dy_resample_ratio_proton_reco_pair_xi_right_multi = 0;
		  TH1* h_data_ratio_proton_reco_pair_xi_right_multi = 0;
		  //TH1* h_elastic_x130_n_ext_fromPV_3 = 0;
		  //TH1* h_inel_el_x130_n_ext_fromPV_3 = 0;
		  //TH1* h_dy_n_ext_fromPV_3 = 0;
		  //TH1* h_data_n_ext_fromPV_3 = 0;

		  f_elastic_x130->GetObject("mumu_mass", h_elastic_x130_mass);
		  f_inel_el_x130->GetObject("mumu_mass", h_inel_el_x130_mass);
		  f_dy->GetObject("mumu_mass", h_dy_mass);
		  f_dy_resample->GetObject("mumu_mass", h_dy_resample_mass);
		  f_data->GetObject("mumu_mass", h_data_mass);
		  f_elastic_x130->GetObject("mumu_pt", h_elastic_x130_pt);
		  f_inel_el_x130->GetObject("mumu_pt", h_inel_el_x130_pt);
		  f_dy->GetObject("mumu_pt", h_dy_pt);
		  f_dy_resample->GetObject("mumu_pt", h_dy_resample_pt);
		  f_data->GetObject("mumu_pt", h_data_pt);
		  f_elastic_x130->GetObject("mumu_y", h_elastic_x130_y);
		  f_inel_el_x130->GetObject("mumu_y", h_inel_el_x130_y);
		  f_dy->GetObject("mumu_y", h_dy_y);
		  f_dy_resample->GetObject("mumu_y", h_dy_resample_y);
		  f_data->GetObject("mumu_y", h_data_y);
		  //f_elastic_x130->GetObject("n_ext_fromPV_3", h_elastic_x130_n_ext_fromPV_3);
		  //f_inel_el_x130->GetObject("n_ext_fromPV_3", h_inel_el_x130_n_ext_fromPV_3);
		  //f_dy->GetObject("n_ext_fromPV_3", h_dy_n_ext_fromPV_3);
		  //f_data->GetObject("n_ext_fromPV_3", h_data_n_ext_fromPV_3);
		  f_elastic_x130->GetObject("proton_xi_left_single", h_elastic_x130_proton_xi_left_single);
		  f_inel_el_x130->GetObject("proton_xi_left_single", h_inel_el_x130_proton_xi_left_single);
		  f_dy->GetObject("proton_xi_left_single", h_dy_proton_xi_left_single);
		  f_dy_resample->GetObject("proton_xi_left_single", h_dy_resample_proton_xi_left_single);
		  f_data->GetObject("proton_xi_left_single", h_data_proton_xi_left_single);
		  f_elastic_x130->GetObject("proton_xi_right_single", h_elastic_x130_proton_xi_right_single);
		  f_inel_el_x130->GetObject("proton_xi_right_single", h_inel_el_x130_proton_xi_right_single);
		  f_dy->GetObject("proton_xi_right_single", h_dy_proton_xi_right_single);
		  f_dy_resample->GetObject("proton_xi_right_single", h_dy_resample_proton_xi_right_single);
		  f_data->GetObject("proton_xi_right_single", h_data_proton_xi_right_single);
		  f_elastic_x130->GetObject("proton_xi_left_multi", h_elastic_x130_proton_xi_left_multi);
		  f_inel_el_x130->GetObject("proton_xi_left_multi", h_inel_el_x130_proton_xi_left_multi);
		  f_dy->GetObject("proton_xi_left_multi", h_dy_proton_xi_left_multi);
		  f_dy_resample->GetObject("proton_xi_left_multi", h_dy_resample_proton_xi_left_multi);
		  f_data->GetObject("proton_xi_left_multi", h_data_proton_xi_left_multi);
		  f_elastic_x130->GetObject("proton_xi_right_multi", h_elastic_x130_proton_xi_right_multi);
		  f_inel_el_x130->GetObject("proton_xi_right_multi", h_inel_el_x130_proton_xi_right_multi);
		  f_dy->GetObject("proton_xi_right_multi", h_dy_proton_xi_right_multi);
		  f_dy_resample->GetObject("proton_xi_right_multi", h_dy_resample_proton_xi_right_multi);
		  f_data->GetObject("proton_xi_right_multi", h_data_proton_xi_right_multi);
		  f_elastic_x130->GetObject("diff_proton_reco_pair_xi_left_single", h_elastic_x130_diff_proton_reco_pair_xi_left_single);
		  f_inel_el_x130->GetObject("diff_proton_reco_pair_xi_left_single", h_inel_el_x130_diff_proton_reco_pair_xi_left_single);
		  f_dy->GetObject("diff_proton_reco_pair_xi_left_single", h_dy_diff_proton_reco_pair_xi_left_single);
		  f_dy_resample->GetObject("diff_proton_reco_pair_xi_left_single", h_dy_resample_diff_proton_reco_pair_xi_left_single);
		  f_data->GetObject("diff_proton_reco_pair_xi_left_single", h_data_diff_proton_reco_pair_xi_left_single);
		  f_elastic_x130->GetObject("diff_proton_reco_pair_xi_right_single", h_elastic_x130_diff_proton_reco_pair_xi_right_single);
		  f_inel_el_x130->GetObject("diff_proton_reco_pair_xi_right_single", h_inel_el_x130_diff_proton_reco_pair_xi_right_single);
		  f_dy->GetObject("diff_proton_reco_pair_xi_right_single", h_dy_diff_proton_reco_pair_xi_right_single);
		  f_dy_resample->GetObject("diff_proton_reco_pair_xi_right_single", h_dy_resample_diff_proton_reco_pair_xi_right_single);
		  f_data->GetObject("diff_proton_reco_pair_xi_right_single", h_data_diff_proton_reco_pair_xi_right_single);
		  f_elastic_x130->GetObject("diff_proton_reco_pair_xi_left_multi", h_elastic_x130_diff_proton_reco_pair_xi_left_multi);
		  f_inel_el_x130->GetObject("diff_proton_reco_pair_xi_left_multi", h_inel_el_x130_diff_proton_reco_pair_xi_left_multi);
		  f_dy->GetObject("diff_proton_reco_pair_xi_left_multi", h_dy_diff_proton_reco_pair_xi_left_multi);
		  f_dy_resample->GetObject("diff_proton_reco_pair_xi_left_multi", h_dy_resample_diff_proton_reco_pair_xi_left_multi);
		  f_data->GetObject("diff_proton_reco_pair_xi_left_multi", h_data_diff_proton_reco_pair_xi_left_multi);
		  f_elastic_x130->GetObject("diff_proton_reco_pair_xi_right_multi", h_elastic_x130_diff_proton_reco_pair_xi_right_multi);
		  f_inel_el_x130->GetObject("diff_proton_reco_pair_xi_right_multi", h_inel_el_x130_diff_proton_reco_pair_xi_right_multi);
		  f_dy->GetObject("diff_proton_reco_pair_xi_right_multi", h_dy_diff_proton_reco_pair_xi_right_multi);
		  f_dy_resample->GetObject("diff_proton_reco_pair_xi_right_multi", h_dy_resample_diff_proton_reco_pair_xi_right_multi);
		  f_data->GetObject("diff_proton_reco_pair_xi_right_multi", h_data_diff_proton_reco_pair_xi_right_multi);
		  f_elastic_x130->GetObject("ratio_proton_reco_pair_xi_left_single", h_elastic_x130_ratio_proton_reco_pair_xi_left_single);
		  f_inel_el_x130->GetObject("ratio_proton_reco_pair_xi_left_single", h_inel_el_x130_ratio_proton_reco_pair_xi_left_single);
		  f_dy->GetObject("ratio_proton_reco_pair_xi_left_single", h_dy_ratio_proton_reco_pair_xi_left_single);
		  f_dy_resample->GetObject("ratio_proton_reco_pair_xi_left_single", h_dy_resample_ratio_proton_reco_pair_xi_left_single);
		  f_data->GetObject("ratio_proton_reco_pair_xi_left_single", h_data_ratio_proton_reco_pair_xi_left_single);
		  f_elastic_x130->GetObject("ratio_proton_reco_pair_xi_right_single", h_elastic_x130_ratio_proton_reco_pair_xi_right_single);
		  f_inel_el_x130->GetObject("ratio_proton_reco_pair_xi_right_single", h_inel_el_x130_ratio_proton_reco_pair_xi_right_single);
		  f_dy->GetObject("ratio_proton_reco_pair_xi_right_single", h_dy_ratio_proton_reco_pair_xi_right_single);
		  f_dy_resample->GetObject("ratio_proton_reco_pair_xi_right_single", h_dy_resample_ratio_proton_reco_pair_xi_right_single);
		  f_data->GetObject("ratio_proton_reco_pair_xi_right_single", h_data_ratio_proton_reco_pair_xi_right_single);
		  f_elastic_x130->GetObject("ratio_proton_reco_pair_xi_left_multi", h_elastic_x130_ratio_proton_reco_pair_xi_left_multi);
		  f_inel_el_x130->GetObject("ratio_proton_reco_pair_xi_left_multi", h_inel_el_x130_ratio_proton_reco_pair_xi_left_multi);
		  f_dy->GetObject("ratio_proton_reco_pair_xi_left_multi", h_dy_ratio_proton_reco_pair_xi_left_multi);
		  f_dy_resample->GetObject("ratio_proton_reco_pair_xi_left_multi", h_dy_resample_ratio_proton_reco_pair_xi_left_multi);
		  f_data->GetObject("ratio_proton_reco_pair_xi_left_multi", h_data_ratio_proton_reco_pair_xi_left_multi);
		  f_elastic_x130->GetObject("ratio_proton_reco_pair_xi_right_multi", h_elastic_x130_ratio_proton_reco_pair_xi_right_multi);
		  f_inel_el_x130->GetObject("ratio_proton_reco_pair_xi_right_multi", h_inel_el_x130_ratio_proton_reco_pair_xi_right_multi);
		  f_dy->GetObject("ratio_proton_reco_pair_xi_right_multi", h_dy_ratio_proton_reco_pair_xi_right_multi);
		  f_dy_resample->GetObject("ratio_proton_reco_pair_xi_right_multi", h_dy_resample_ratio_proton_reco_pair_xi_right_multi);
		  f_data->GetObject("ratio_proton_reco_pair_xi_right_multi", h_data_ratio_proton_reco_pair_xi_right_multi);

        double n_events_h_elastic_x130 = 200000;
        double n_events_h_inel_el_x130 = 200000;
        double n_events_h_dy = 48675378;
        double n_events_pileup = 18964805;
		  double number_of_samples = 0.01;

		  scale_factor_elastic_x130 = eff_trigger_elastic_x130*37.022*0.017254036*1000 / n_events_h_elastic_x130 ; //
		  scale_factor_inel_el_x130 = eff_trigger_inel_el_x130*37.022*0.025643100*1000 / n_events_h_inel_el_x130 ; //
		  scale_factor_dy = event_selection*eff_trigger_dy*37.022*5334000 / n_events_h_dy; 
		  scale_factor_dy_resample = event_selection*eff_trigger_dy*37.022*5334000 / n_events_h_dy*number_of_samples; 

		  h_elastic_x130_mass->SetLineColor(kBlue);
		  h_inel_el_x130_mass->SetLineColor(kGreen);
		  h_dy_mass->SetLineColor(kRed);
		  h_dy_resample_mass->SetLineColor(kRed);
		  h_elastic_x130_mass->SetFillColor(kBlue);
		  h_inel_el_x130_mass->SetFillColor(kGreen);
		  h_dy_mass->SetFillColor(kRed);
		  h_dy_resample_mass->SetFillColor(kRed);
		  h_elastic_x130_mass->GetXaxis()->SetTitle("M_{#mu^{+}#mu^{-}} (GeV/c^{2})");
		  h_elastic_x130_mass->GetYaxis()->SetTitle("Events");
		  h_inel_el_x130_mass->GetXaxis()->SetTitle("M_{#mu^{+}#mu^{-}} (GeV/c^{2})");
		  h_inel_el_x130_mass->GetYaxis()->SetTitle("Events");
		  h_dy_mass->GetXaxis()->SetTitle("M_{#mu^{+}#mu^{-}} (GeV/c^{2})");
		  h_dy_mass->GetYaxis()->SetTitle("Events");
		  h_dy_resample_mass->GetXaxis()->SetTitle("M_{#mu^{+}#mu^{-}} (GeV/c^{2})");
		  h_dy_resample_mass->GetYaxis()->SetTitle("Events");
		  h_data_mass->GetXaxis()->SetTitle("M_{#mu^{+}#mu^{-}} (GeV/c^{2})");
		  h_data_mass->GetYaxis()->SetTitle("Events");
		  h_data_mass->SetMarkerStyle(8);
		  h_data_mass->Sumw2();
		  h_elastic_x130_pt->SetLineColor(kBlue);
		  h_inel_el_x130_pt->SetLineColor(kGreen);
		  h_dy_pt->SetLineColor(kRed);
		  h_dy_resample_pt->SetLineColor(kRed);
		  h_elastic_x130_pt->SetFillColor(kBlue);
		  h_inel_el_x130_pt->SetFillColor(kGreen);
		  h_dy_pt->SetFillColor(kRed);
		  h_dy_resample_pt->SetFillColor(kRed);
		  h_elastic_x130_pt->GetXaxis()->SetTitle("p_{T}_{#mu^{+}#mu^{-}} (GeV/c)");
		  h_elastic_x130_pt->GetYaxis()->SetTitle("Events");
		  h_inel_el_x130_pt->GetXaxis()->SetTitle("p_{T}_{#mu^{+}#mu^{-}} (GeV/c)");
		  h_inel_el_x130_pt->GetYaxis()->SetTitle("Events");
		  h_dy_pt->GetXaxis()->SetTitle("p_{T}_{#mu^{+}#mu^{-}} (GeV/c)");
		  h_dy_pt->GetYaxis()->SetTitle("Events");
		  h_dy_resample_pt->GetXaxis()->SetTitle("p_{T}_{#mu^{+}#mu^{-}} (GeV/c)");
		  h_dy_resample_pt->GetYaxis()->SetTitle("Events");
		  h_data_pt->GetXaxis()->SetTitle("p_{T}_{#mu^{+}#mu^{-}} (GeV/c)");
		  h_data_pt->GetYaxis()->SetTitle("Events");
		  h_data_pt->SetMarkerStyle(8);
		  h_data_pt->Sumw2();
		  h_elastic_x130_y->SetLineColor(kBlue);
		  h_inel_el_x130_y->SetLineColor(kGreen);
		  h_dy_y->SetLineColor(kRed);
		  h_dy_resample_y->SetLineColor(kRed);
		  h_elastic_x130_y->SetFillColor(kBlue);
		  h_inel_el_x130_y->SetFillColor(kGreen);
		  h_dy_y->SetFillColor(kRed);
		  h_dy_resample_y->SetFillColor(kRed);
		  h_elastic_x130_y->GetXaxis()->SetTitle("y_{#mu^{+}#mu^{-}}");
		  h_elastic_x130_y->GetYaxis()->SetTitle("Events");
		  h_inel_el_x130_y->GetXaxis()->SetTitle("y_{#mu^{+}#mu^{-}}");
		  h_inel_el_x130_y->GetYaxis()->SetTitle("Events");
		  h_dy_y->GetXaxis()->SetTitle("y_{#mu^{+}#mu^{-}}");
		  h_dy_y->GetYaxis()->SetTitle("Events");
		  h_dy_resample_y->GetXaxis()->SetTitle("y_{#mu^{+}#mu^{-}}");
		  h_dy_resample_y->GetYaxis()->SetTitle("Events");
		  h_data_y->GetXaxis()->SetTitle("y_{#mu^{+}#mu^{-}}");
		  h_data_y->GetYaxis()->SetTitle("Events");
		  h_data_y->SetMarkerStyle(8);
		  h_data_y->Sumw2();
		  //h_elastic_x130_n_ext_fromPV_3->SetLineColor(kBlue);
		  //h_inel_el_x130_n_ext_fromPV_3->SetLineColor(kGreen);
		  //h_dy_n_ext_fromPV_3->SetLineColor(kRed);
		  //h_elastic_x130_n_ext_fromPV_3->SetFillColor(kBlue);
		  //h_inel_el_x130_n_ext_fromPV_3->SetFillColor(kGreen);
		  //h_dy_n_ext_fromPV_3->SetFillColor(kRed);
		  //h_data_n_ext_fromPV_3->SetMarkerStyle(8);
		  //h_data_n_ext_fromPV_3->Sumw2();
		  h_elastic_x130_proton_xi_left_single->SetLineColor(kBlue);
		  h_inel_el_x130_proton_xi_left_single->SetLineColor(kGreen);
		  h_dy_proton_xi_left_single->SetLineColor(kRed);
		  h_dy_resample_proton_xi_left_single->SetLineColor(kRed);
		  h_elastic_x130_proton_xi_left_single->SetFillColor(kBlue);
		  h_inel_el_x130_proton_xi_left_single->SetFillColor(kGreen);
		  h_dy_proton_xi_left_single->SetFillColor(kRed);
		  h_dy_resample_proton_xi_left_single->SetFillColor(kRed);
		  h_elastic_x130_proton_xi_left_single->GetXaxis()->SetTitle("#xi(RP)");
		  h_elastic_x130_proton_xi_left_single->GetYaxis()->SetTitle("Events");
		  h_inel_el_x130_proton_xi_left_single->GetXaxis()->SetTitle("#xi(RP)");
		  h_inel_el_x130_proton_xi_left_single->GetYaxis()->SetTitle("Events");
		  h_dy_proton_xi_left_single->GetXaxis()->SetTitle("#xi(RP)");
		  h_dy_proton_xi_left_single->GetYaxis()->SetTitle("Events");
		  h_dy_resample_proton_xi_left_single->GetXaxis()->SetTitle("#xi(RP)");
		  h_dy_resample_proton_xi_left_single->GetYaxis()->SetTitle("Events");
		  h_data_proton_xi_left_single->GetXaxis()->SetTitle("#xi(RP)");
		  h_data_proton_xi_left_single->GetYaxis()->SetTitle("Events");
		  h_data_proton_xi_left_single->SetMarkerStyle(8);
		  h_data_proton_xi_left_single->Sumw2();
		  h_elastic_x130_proton_xi_right_single->SetLineColor(kBlue);
		  h_inel_el_x130_proton_xi_right_single->SetLineColor(kGreen);
		  h_dy_proton_xi_right_single->SetLineColor(kRed);
		  h_dy_resample_proton_xi_right_single->SetLineColor(kRed);
		  h_elastic_x130_proton_xi_right_single->SetFillColor(kBlue);
		  h_inel_el_x130_proton_xi_right_single->SetFillColor(kGreen);
		  h_dy_proton_xi_right_single->SetFillColor(kRed);
		  h_dy_resample_proton_xi_right_single->SetFillColor(kRed);
		  h_elastic_x130_proton_xi_right_single->GetXaxis()->SetTitle("#xi(RP)");
		  h_elastic_x130_proton_xi_right_single->GetYaxis()->SetTitle("Events");
		  h_inel_el_x130_proton_xi_right_single->GetXaxis()->SetTitle("#xi(RP)");
		  h_inel_el_x130_proton_xi_right_single->GetYaxis()->SetTitle("Events");
		  h_dy_proton_xi_right_single->GetXaxis()->SetTitle("#xi(RP)");
		  h_dy_proton_xi_right_single->GetYaxis()->SetTitle("Events");
		  h_dy_resample_proton_xi_right_single->GetXaxis()->SetTitle("#xi(RP)");
		  h_dy_resample_proton_xi_right_single->GetYaxis()->SetTitle("Events");
		  h_data_proton_xi_right_single->GetXaxis()->SetTitle("#xi(RP)");
		  h_data_proton_xi_right_single->GetYaxis()->SetTitle("Events");
		  h_data_proton_xi_right_single->SetMarkerStyle(8);
		  h_data_proton_xi_right_single->Sumw2();
		  h_elastic_x130_proton_xi_left_multi->SetLineColor(kBlue);
		  h_inel_el_x130_proton_xi_left_multi->SetLineColor(kGreen);
		  h_dy_proton_xi_left_multi->SetLineColor(kRed);
		  h_dy_resample_proton_xi_left_multi->SetLineColor(kRed);
		  h_elastic_x130_proton_xi_left_multi->SetFillColor(kBlue);
		  h_inel_el_x130_proton_xi_left_multi->SetFillColor(kGreen);
		  h_dy_proton_xi_left_multi->SetFillColor(kRed);
		  h_dy_resample_proton_xi_left_multi->SetFillColor(kRed);
		  h_elastic_x130_proton_xi_left_multi->GetXaxis()->SetTitle("#xi(RP)");
		  h_elastic_x130_proton_xi_left_multi->GetYaxis()->SetTitle("Events");
		  h_inel_el_x130_proton_xi_left_multi->GetXaxis()->SetTitle("#xi(RP)");
		  h_inel_el_x130_proton_xi_left_multi->GetYaxis()->SetTitle("Events");
		  h_dy_proton_xi_left_multi->GetXaxis()->SetTitle("#xi(RP)");
		  h_dy_proton_xi_left_multi->GetYaxis()->SetTitle("Events");
		  h_dy_resample_proton_xi_left_multi->GetXaxis()->SetTitle("#xi(RP)");
		  h_dy_resample_proton_xi_left_multi->GetYaxis()->SetTitle("Events");
		  h_data_proton_xi_left_multi->GetXaxis()->SetTitle("#xi(RP)");
		  h_data_proton_xi_left_multi->GetYaxis()->SetTitle("Events");
		  h_data_proton_xi_left_multi->SetMarkerStyle(8);
		  h_data_proton_xi_left_multi->Sumw2();
		  h_elastic_x130_proton_xi_right_multi->SetLineColor(kBlue);
		  h_inel_el_x130_proton_xi_right_multi->SetLineColor(kGreen);
		  h_dy_proton_xi_right_multi->SetLineColor(kRed);
		  h_dy_resample_proton_xi_right_multi->SetLineColor(kRed);
		  h_elastic_x130_proton_xi_right_multi->SetFillColor(kBlue);
		  h_inel_el_x130_proton_xi_right_multi->SetFillColor(kGreen);
		  h_dy_proton_xi_right_multi->SetFillColor(kRed);
		  h_dy_resample_proton_xi_right_multi->SetFillColor(kRed);
		  h_elastic_x130_proton_xi_right_multi->GetXaxis()->SetTitle("#xi(RP)");
		  h_elastic_x130_proton_xi_right_multi->GetYaxis()->SetTitle("Events");
		  h_inel_el_x130_proton_xi_right_multi->GetXaxis()->SetTitle("#xi(RP)");
		  h_inel_el_x130_proton_xi_right_multi->GetYaxis()->SetTitle("Events");
		  h_dy_proton_xi_right_multi->GetXaxis()->SetTitle("#xi(RP)");
		  h_dy_proton_xi_right_multi->GetYaxis()->SetTitle("Events");
		  h_dy_resample_proton_xi_right_multi->GetXaxis()->SetTitle("#xi(RP)");
		  h_dy_resample_proton_xi_right_multi->GetYaxis()->SetTitle("Events");
		  h_data_proton_xi_right_multi->GetXaxis()->SetTitle("#xi(RP)");
		  h_data_proton_xi_right_multi->GetYaxis()->SetTitle("Events");
		  h_data_proton_xi_right_multi->SetMarkerStyle(8);
		  h_data_proton_xi_right_multi->Sumw2();
		  h_elastic_x130_diff_proton_reco_pair_xi_left_single->SetLineColor(kBlue);
		  h_inel_el_x130_diff_proton_reco_pair_xi_left_single->SetLineColor(kGreen);
		  h_dy_diff_proton_reco_pair_xi_left_single->SetLineColor(kRed);
		  h_dy_resample_diff_proton_reco_pair_xi_left_single->SetLineColor(kRed);
		  h_elastic_x130_diff_proton_reco_pair_xi_left_single->SetFillColor(kBlue);
		  h_inel_el_x130_diff_proton_reco_pair_xi_left_single->SetFillColor(kGreen);
		  h_dy_diff_proton_reco_pair_xi_left_single->SetFillColor(kRed);
		  h_dy_resample_diff_proton_reco_pair_xi_left_single->SetFillColor(kRed);
		  h_elastic_x130_diff_proton_reco_pair_xi_left_single->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_elastic_x130_diff_proton_reco_pair_xi_left_single->SetTitle("Events");
		  h_inel_el_x130_diff_proton_reco_pair_xi_left_single->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_inel_el_x130_diff_proton_reco_pair_xi_left_single->GetYaxis()->SetTitle("Events");
		  h_dy_diff_proton_reco_pair_xi_left_single->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_dy_diff_proton_reco_pair_xi_left_single->GetYaxis()->SetTitle("Events");
		  h_dy_resample_diff_proton_reco_pair_xi_left_single->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_dy_resample_diff_proton_reco_pair_xi_left_single->GetYaxis()->SetTitle("Events");
		  h_data_diff_proton_reco_pair_xi_left_single->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_data_diff_proton_reco_pair_xi_left_single->GetYaxis()->SetTitle("Events");
		  h_data_diff_proton_reco_pair_xi_left_single->SetMarkerStyle(8);
		  h_data_diff_proton_reco_pair_xi_left_single->Sumw2();
		  h_elastic_x130_diff_proton_reco_pair_xi_right_single->SetLineColor(kBlue);
		  h_inel_el_x130_diff_proton_reco_pair_xi_right_single->SetLineColor(kGreen);
		  h_dy_diff_proton_reco_pair_xi_right_single->SetLineColor(kRed);
		  h_dy_resample_diff_proton_reco_pair_xi_right_single->SetLineColor(kRed);
		  h_elastic_x130_diff_proton_reco_pair_xi_right_single->SetFillColor(kBlue);
		  h_inel_el_x130_diff_proton_reco_pair_xi_right_single->SetFillColor(kGreen);
		  h_dy_diff_proton_reco_pair_xi_right_single->SetFillColor(kRed);
		  h_dy_resample_diff_proton_reco_pair_xi_right_single->SetFillColor(kRed);
		  h_elastic_x130_diff_proton_reco_pair_xi_right_single->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_elastic_x130_diff_proton_reco_pair_xi_right_single->SetTitle("Events");
		  h_inel_el_x130_diff_proton_reco_pair_xi_right_single->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_inel_el_x130_diff_proton_reco_pair_xi_right_single->GetYaxis()->SetTitle("Events");
		  h_dy_diff_proton_reco_pair_xi_right_single->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_dy_diff_proton_reco_pair_xi_right_single->GetYaxis()->SetTitle("Events");
		  h_dy_resample_diff_proton_reco_pair_xi_right_single->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_dy_resample_diff_proton_reco_pair_xi_right_single->GetYaxis()->SetTitle("Events");
		  h_data_diff_proton_reco_pair_xi_right_single->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_data_diff_proton_reco_pair_xi_right_single->GetYaxis()->SetTitle("Events");
		  h_data_diff_proton_reco_pair_xi_right_single->SetMarkerStyle(8);
		  h_data_diff_proton_reco_pair_xi_right_single->Sumw2();
		  h_elastic_x130_diff_proton_reco_pair_xi_left_multi->SetLineColor(kBlue);
		  h_inel_el_x130_diff_proton_reco_pair_xi_left_multi->SetLineColor(kGreen);
		  h_dy_diff_proton_reco_pair_xi_left_multi->SetLineColor(kRed);
		  h_dy_resample_diff_proton_reco_pair_xi_left_multi->SetLineColor(kRed);
		  h_elastic_x130_diff_proton_reco_pair_xi_left_multi->SetFillColor(kBlue);
		  h_inel_el_x130_diff_proton_reco_pair_xi_left_multi->SetFillColor(kGreen);
		  h_dy_diff_proton_reco_pair_xi_left_multi->SetFillColor(kRed);
		  h_dy_resample_diff_proton_reco_pair_xi_left_multi->SetFillColor(kRed);
		  h_elastic_x130_diff_proton_reco_pair_xi_left_multi->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_elastic_x130_diff_proton_reco_pair_xi_left_multi->SetTitle("Events");
		  h_inel_el_x130_diff_proton_reco_pair_xi_left_multi->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_inel_el_x130_diff_proton_reco_pair_xi_left_multi->GetYaxis()->SetTitle("Events");
		  h_dy_diff_proton_reco_pair_xi_left_multi->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_dy_diff_proton_reco_pair_xi_left_multi->GetYaxis()->SetTitle("Events");
		  h_dy_resample_diff_proton_reco_pair_xi_left_multi->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_dy_resample_diff_proton_reco_pair_xi_left_multi->GetYaxis()->SetTitle("Events");
		  h_data_diff_proton_reco_pair_xi_left_multi->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_data_diff_proton_reco_pair_xi_left_multi->GetYaxis()->SetTitle("Events");
		  h_data_diff_proton_reco_pair_xi_left_multi->SetMarkerStyle(8);
		  h_data_diff_proton_reco_pair_xi_left_multi->Sumw2();
		  h_elastic_x130_diff_proton_reco_pair_xi_right_multi->SetLineColor(kBlue);
		  h_inel_el_x130_diff_proton_reco_pair_xi_right_multi->SetLineColor(kGreen);
		  h_dy_diff_proton_reco_pair_xi_right_multi->SetLineColor(kRed);
		  h_dy_resample_diff_proton_reco_pair_xi_right_multi->SetLineColor(kRed);
		  h_elastic_x130_diff_proton_reco_pair_xi_right_multi->SetFillColor(kBlue);
		  h_inel_el_x130_diff_proton_reco_pair_xi_right_multi->SetFillColor(kGreen);
		  h_dy_diff_proton_reco_pair_xi_right_multi->SetFillColor(kRed);
		  h_dy_resample_diff_proton_reco_pair_xi_right_multi->SetFillColor(kRed);
		  h_elastic_x130_diff_proton_reco_pair_xi_right_multi->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_elastic_x130_diff_proton_reco_pair_xi_right_multi->SetTitle("Events");
		  h_inel_el_x130_diff_proton_reco_pair_xi_right_multi->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_inel_el_x130_diff_proton_reco_pair_xi_right_multi->GetYaxis()->SetTitle("Events");
		  h_dy_diff_proton_reco_pair_xi_right_multi->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_dy_diff_proton_reco_pair_xi_right_multi->GetYaxis()->SetTitle("Events");
		  h_dy_resample_diff_proton_reco_pair_xi_right_multi->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_dy_resample_diff_proton_reco_pair_xi_right_multi->GetYaxis()->SetTitle("Events");
		  h_data_diff_proton_reco_pair_xi_right_multi->GetXaxis()->SetTitle("#xi(RP) - #xi({#mu^{+}#mu^{-}})");
		  h_data_diff_proton_reco_pair_xi_right_multi->GetYaxis()->SetTitle("Events");
		  h_data_diff_proton_reco_pair_xi_right_multi->SetMarkerStyle(8);
		  h_data_diff_proton_reco_pair_xi_right_multi->Sumw2();
		  h_elastic_x130_ratio_proton_reco_pair_xi_left_single->SetLineColor(kBlue);
		  h_inel_el_x130_ratio_proton_reco_pair_xi_left_single->SetLineColor(kGreen);
		  h_dy_ratio_proton_reco_pair_xi_left_single->SetLineColor(kRed);
		  h_dy_resample_ratio_proton_reco_pair_xi_left_single->SetLineColor(kRed);
		  h_elastic_x130_ratio_proton_reco_pair_xi_left_single->SetFillColor(kBlue);
		  h_inel_el_x130_ratio_proton_reco_pair_xi_left_single->SetFillColor(kGreen);
		  h_dy_ratio_proton_reco_pair_xi_left_single->SetFillColor(kRed);
		  h_dy_resample_ratio_proton_reco_pair_xi_left_single->SetFillColor(kRed);
		  h_elastic_x130_ratio_proton_reco_pair_xi_left_single->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_elastic_x130_ratio_proton_reco_pair_xi_left_single->SetTitle("Events");
		  h_inel_el_x130_ratio_proton_reco_pair_xi_left_single->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_inel_el_x130_ratio_proton_reco_pair_xi_left_single->GetYaxis()->SetTitle("Events");
		  h_dy_ratio_proton_reco_pair_xi_left_single->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_dy_ratio_proton_reco_pair_xi_left_single->GetYaxis()->SetTitle("Events");
		  h_dy_resample_ratio_proton_reco_pair_xi_left_single->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_dy_resample_ratio_proton_reco_pair_xi_left_single->GetYaxis()->SetTitle("Events");
		  h_data_ratio_proton_reco_pair_xi_left_single->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_data_ratio_proton_reco_pair_xi_left_single->GetYaxis()->SetTitle("Events");
		  h_data_ratio_proton_reco_pair_xi_left_single->SetMarkerStyle(8);
		  h_data_ratio_proton_reco_pair_xi_left_single->Sumw2();
		  h_elastic_x130_ratio_proton_reco_pair_xi_right_single->SetLineColor(kBlue);
		  h_inel_el_x130_ratio_proton_reco_pair_xi_right_single->SetLineColor(kGreen);
		  h_dy_ratio_proton_reco_pair_xi_right_single->SetLineColor(kRed);
		  h_dy_resample_ratio_proton_reco_pair_xi_right_single->SetLineColor(kRed);
		  h_elastic_x130_ratio_proton_reco_pair_xi_right_single->SetFillColor(kBlue);
		  h_inel_el_x130_ratio_proton_reco_pair_xi_right_single->SetFillColor(kGreen);
		  h_dy_ratio_proton_reco_pair_xi_right_single->SetFillColor(kRed);
		  h_dy_resample_ratio_proton_reco_pair_xi_right_single->SetFillColor(kRed);
		  h_elastic_x130_ratio_proton_reco_pair_xi_right_single->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_elastic_x130_ratio_proton_reco_pair_xi_right_single->SetTitle("Events");
		  h_inel_el_x130_ratio_proton_reco_pair_xi_right_single->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_inel_el_x130_ratio_proton_reco_pair_xi_right_single->GetYaxis()->SetTitle("Events");
		  h_dy_ratio_proton_reco_pair_xi_right_single->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_dy_ratio_proton_reco_pair_xi_right_single->GetYaxis()->SetTitle("Events");
		  h_dy_resample_ratio_proton_reco_pair_xi_right_single->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_dy_resample_ratio_proton_reco_pair_xi_right_single->GetYaxis()->SetTitle("Events");
		  h_data_ratio_proton_reco_pair_xi_right_single->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_data_ratio_proton_reco_pair_xi_right_single->GetYaxis()->SetTitle("Events");
		  h_data_ratio_proton_reco_pair_xi_right_single->SetMarkerStyle(8);
		  h_data_ratio_proton_reco_pair_xi_right_single->Sumw2();
		  h_elastic_x130_ratio_proton_reco_pair_xi_left_multi->SetLineColor(kBlue);
		  h_inel_el_x130_ratio_proton_reco_pair_xi_left_multi->SetLineColor(kGreen);
		  h_dy_ratio_proton_reco_pair_xi_left_multi->SetLineColor(kRed);
		  h_dy_resample_ratio_proton_reco_pair_xi_left_multi->SetLineColor(kRed);
		  h_elastic_x130_ratio_proton_reco_pair_xi_left_multi->SetFillColor(kBlue);
		  h_inel_el_x130_ratio_proton_reco_pair_xi_left_multi->SetFillColor(kGreen);
		  h_dy_ratio_proton_reco_pair_xi_left_multi->SetFillColor(kRed);
		  h_dy_resample_ratio_proton_reco_pair_xi_left_multi->SetFillColor(kRed);
		  h_elastic_x130_ratio_proton_reco_pair_xi_left_multi->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_elastic_x130_ratio_proton_reco_pair_xi_left_multi->SetTitle("Events");
		  h_inel_el_x130_ratio_proton_reco_pair_xi_left_multi->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_inel_el_x130_ratio_proton_reco_pair_xi_left_multi->GetYaxis()->SetTitle("Events");
		  h_dy_ratio_proton_reco_pair_xi_left_multi->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_dy_ratio_proton_reco_pair_xi_left_multi->GetYaxis()->SetTitle("Events");
		  h_dy_resample_ratio_proton_reco_pair_xi_left_multi->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_dy_resample_ratio_proton_reco_pair_xi_left_multi->GetYaxis()->SetTitle("Events");
		  h_data_ratio_proton_reco_pair_xi_left_multi->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_data_ratio_proton_reco_pair_xi_left_multi->GetYaxis()->SetTitle("Events");
		  h_data_ratio_proton_reco_pair_xi_left_multi->SetMarkerStyle(8);
		  h_data_ratio_proton_reco_pair_xi_left_multi->Sumw2();
		  h_elastic_x130_ratio_proton_reco_pair_xi_right_multi->SetLineColor(kBlue);
		  h_inel_el_x130_ratio_proton_reco_pair_xi_right_multi->SetLineColor(kGreen);
		  h_dy_ratio_proton_reco_pair_xi_right_multi->SetLineColor(kRed);
		  h_dy_resample_ratio_proton_reco_pair_xi_right_multi->SetLineColor(kRed);
		  h_elastic_x130_ratio_proton_reco_pair_xi_right_multi->SetFillColor(kBlue);
		  h_inel_el_x130_ratio_proton_reco_pair_xi_right_multi->SetFillColor(kGreen);
		  h_dy_ratio_proton_reco_pair_xi_right_multi->SetFillColor(kRed);
		  h_dy_resample_ratio_proton_reco_pair_xi_right_multi->SetFillColor(kRed);
		  h_elastic_x130_ratio_proton_reco_pair_xi_right_multi->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_elastic_x130_ratio_proton_reco_pair_xi_right_multi->SetTitle("Events");
		  h_inel_el_x130_ratio_proton_reco_pair_xi_right_multi->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_inel_el_x130_ratio_proton_reco_pair_xi_right_multi->GetYaxis()->SetTitle("Events");
		  h_dy_ratio_proton_reco_pair_xi_right_multi->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_dy_ratio_proton_reco_pair_xi_right_multi->GetYaxis()->SetTitle("Events");
		  h_dy_resample_ratio_proton_reco_pair_xi_right_multi->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_dy_resample_ratio_proton_reco_pair_xi_right_multi->GetYaxis()->SetTitle("Events");
		  h_data_ratio_proton_reco_pair_xi_right_multi->GetXaxis()->SetTitle("1 - #xi(RP)/#xi({#mu^{+}#mu^{-}})");
		  h_data_ratio_proton_reco_pair_xi_right_multi->GetYaxis()->SetTitle("Events");
		  h_data_ratio_proton_reco_pair_xi_right_multi->SetMarkerStyle(8);
		  h_data_ratio_proton_reco_pair_xi_right_multi->Sumw2();
		  
		  h_elastic_x130_mass->Scale(scale_factor_elastic_x130);
		  h_inel_el_x130_mass->Scale(scale_factor_inel_el_x130);
		  h_dy_mass->Scale(scale_factor_dy);
		  h_dy_resample_mass->Scale(scale_factor_dy_resample);
		  h_elastic_x130_pt->Scale(scale_factor_elastic_x130);
		  h_inel_el_x130_pt->Scale(scale_factor_inel_el_x130);
		  h_dy_pt->Scale(scale_factor_dy);
		  h_dy_resample_pt->Scale(scale_factor_dy_resample);
		  h_elastic_x130_y->Scale(scale_factor_elastic_x130);
		  h_inel_el_x130_y->Scale(scale_factor_inel_el_x130);
		  h_dy_y->Scale(scale_factor_dy);
		  h_dy_resample_y->Scale(scale_factor_dy_resample);
		  h_elastic_x130_proton_xi_left_single->Scale(scale_factor_elastic_x130);
		  h_inel_el_x130_proton_xi_left_single->Scale(scale_factor_inel_el_x130);
		  h_dy_proton_xi_left_single->Scale(scale_factor_dy);
		  h_dy_resample_proton_xi_left_single->Scale(scale_factor_dy_resample);
		  h_elastic_x130_proton_xi_right_single->Scale(scale_factor_elastic_x130);
		  h_inel_el_x130_proton_xi_right_single->Scale(scale_factor_inel_el_x130);
		  h_dy_proton_xi_right_single->Scale(scale_factor_dy);
		  h_dy_resample_proton_xi_right_single->Scale(scale_factor_dy_resample);
		  h_elastic_x130_proton_xi_left_multi->Scale(scale_factor_elastic_x130);
		  h_inel_el_x130_proton_xi_left_multi->Scale(scale_factor_inel_el_x130);
		  h_dy_proton_xi_left_multi->Scale(scale_factor_dy);
		  h_dy_resample_proton_xi_left_multi->Scale(scale_factor_dy_resample);
		  h_elastic_x130_proton_xi_right_multi->Scale(scale_factor_elastic_x130);
		  h_inel_el_x130_proton_xi_right_multi->Scale(scale_factor_inel_el_x130);
		  h_dy_proton_xi_right_multi->Scale(scale_factor_dy);
		  h_dy_resample_proton_xi_right_multi->Scale(scale_factor_dy_resample);
		  h_elastic_x130_diff_proton_reco_pair_xi_left_single->Scale(scale_factor_elastic_x130);
		  h_inel_el_x130_diff_proton_reco_pair_xi_left_single->Scale(scale_factor_inel_el_x130);
		  h_dy_diff_proton_reco_pair_xi_left_single->Scale(scale_factor_dy);
		  h_dy_resample_diff_proton_reco_pair_xi_left_single->Scale(scale_factor_dy_resample);
		  h_elastic_x130_diff_proton_reco_pair_xi_right_single->Scale(scale_factor_elastic_x130);
		  h_inel_el_x130_diff_proton_reco_pair_xi_right_single->Scale(scale_factor_inel_el_x130);
		  h_dy_diff_proton_reco_pair_xi_right_single->Scale(scale_factor_dy);
		  h_dy_resample_diff_proton_reco_pair_xi_right_single->Scale(scale_factor_dy_resample);
		  h_elastic_x130_diff_proton_reco_pair_xi_left_multi->Scale(scale_factor_elastic_x130);
		  h_inel_el_x130_diff_proton_reco_pair_xi_left_multi->Scale(scale_factor_inel_el_x130);
		  h_dy_diff_proton_reco_pair_xi_left_multi->Scale(scale_factor_dy);
		  h_dy_resample_diff_proton_reco_pair_xi_left_multi->Scale(scale_factor_dy_resample);
		  h_elastic_x130_diff_proton_reco_pair_xi_right_multi->Scale(scale_factor_elastic_x130);
		  h_inel_el_x130_diff_proton_reco_pair_xi_right_multi->Scale(scale_factor_inel_el_x130);
		  h_dy_diff_proton_reco_pair_xi_right_multi->Scale(scale_factor_dy);
		  h_dy_resample_diff_proton_reco_pair_xi_right_multi->Scale(scale_factor_dy_resample);
		  h_elastic_x130_ratio_proton_reco_pair_xi_left_single->Scale(scale_factor_elastic_x130);
		  h_inel_el_x130_ratio_proton_reco_pair_xi_left_single->Scale(scale_factor_inel_el_x130);
		  h_dy_ratio_proton_reco_pair_xi_left_single->Scale(scale_factor_dy);
		  h_dy_resample_ratio_proton_reco_pair_xi_left_single->Scale(scale_factor_dy_resample);
		  h_elastic_x130_ratio_proton_reco_pair_xi_right_single->Scale(scale_factor_elastic_x130);
		  h_inel_el_x130_ratio_proton_reco_pair_xi_right_single->Scale(scale_factor_inel_el_x130);
		  h_dy_ratio_proton_reco_pair_xi_right_single->Scale(scale_factor_dy);
		  h_dy_resample_ratio_proton_reco_pair_xi_right_single->Scale(scale_factor_dy_resample);
		  h_elastic_x130_ratio_proton_reco_pair_xi_left_multi->Scale(scale_factor_elastic_x130);
		  h_inel_el_x130_ratio_proton_reco_pair_xi_left_multi->Scale(scale_factor_inel_el_x130);
		  h_dy_ratio_proton_reco_pair_xi_left_multi->Scale(scale_factor_dy);
		  h_dy_resample_ratio_proton_reco_pair_xi_left_multi->Scale(scale_factor_dy_resample);
		  h_elastic_x130_ratio_proton_reco_pair_xi_right_multi->Scale(scale_factor_elastic_x130);
		  h_inel_el_x130_ratio_proton_reco_pair_xi_right_multi->Scale(scale_factor_inel_el_x130);
		  h_dy_ratio_proton_reco_pair_xi_right_multi->Scale(scale_factor_dy);
		  h_dy_resample_ratio_proton_reco_pair_xi_right_multi->Scale(scale_factor_dy_resample);
		  
        double integral_h_elastic_x130 = h_elastic_x130_mass->Integral( 0, ( h_elastic_x130_mass->GetNbinsX() + 1 ) ); // With under and overflow
        double integral_h_inel_el_x130 = h_inel_el_x130_mass->Integral( 0, ( h_inel_el_x130_mass->GetNbinsX() + 1 ) ); // With under and overflow
        double integral_h_dy = h_dy_mass->Integral( 0, ( h_dy_mass->GetNbinsX() + 1 ) ); // With under and overflow
        double sum_integral = integral_h_elastic_x130 + integral_h_inel_el_x130 + integral_h_dy;
        double scale_data = h_data_mass->GetEntries() / sum_integral ;
        cout << "Scale factor data normalization: " << scale_data << endl;        
       
        // Clone MC histograms and scale
        
        TH1F *h_elastic_x130_clone_mass = (TH1F*)h_elastic_x130_mass->Clone("h_elastic_x130_clone_mass");
        TH1F *h_inel_el_x130_clone_mass = (TH1F*)h_inel_el_x130_mass->Clone("h_inel_el_x130_clone_mass");
        TH1F *h_dy_clone_mass = (TH1F*)h_dy_mass->Clone("h_dy_clone_mass");
        TH1F *h_elastic_x130_clone_pt = (TH1F*)h_elastic_x130_pt->Clone("h_elastic_x130_clone_pt");
        TH1F *h_inel_el_x130_clone_pt = (TH1F*)h_inel_el_x130_pt->Clone("h_inel_el_x130_clone_pt");
        TH1F *h_dy_clone_pt = (TH1F*)h_dy_pt->Clone("h_dy_clone_pt");
        TH1F *h_elastic_x130_clone_y = (TH1F*)h_elastic_x130_y->Clone("h_elastic_x130_clone_y");
        TH1F *h_inel_el_x130_clone_y = (TH1F*)h_inel_el_x130_y->Clone("h_inel_el_x130_clone_y");
        TH1F *h_dy_clone_y = (TH1F*)h_dy_y->Clone("h_dy_clone_y");
		  
        h_elastic_x130_clone_mass->Scale(scale_data);
        h_inel_el_x130_clone_mass->Scale(scale_data);
        h_dy_clone_mass->Scale(scale_data);
        h_elastic_x130_clone_pt->Scale(scale_data);
        h_inel_el_x130_clone_pt->Scale(scale_data);
        h_dy_clone_pt->Scale(scale_data);
        h_elastic_x130_clone_y->Scale(scale_data);
        h_inel_el_x130_clone_y->Scale(scale_data);
        h_dy_clone_y->Scale(scale_data);
		  
		  THStack hs_mass("hs_mass","#mu^{+}#mu^{-} Mass;M_{#mu^{+}#mu^{-}} (GeV/c^{2});Events");
		  hs_mass.Add(h_elastic_x130_mass);
		  hs_mass.Add(h_inel_el_x130_mass);
		  hs_mass.Add(h_dy_mass);
		  THStack hs_pt("hs_pt","#mu^{+}#mu^{-} p_{T};p_{T #mu^{+}#mu^{-}} (GeV/c);Events");
		  hs_pt.Add(h_elastic_x130_pt);
		  hs_pt.Add(h_inel_el_x130_pt);
		  hs_pt.Add(h_dy_pt);
		  THStack hs_y("hs_y","#mu^{+}#mu^{-} y;y_{#mu^{+}#mu^{-}};Events");
		  hs_y.Add(h_elastic_x130_y);
		  hs_y.Add(h_inel_el_x130_y);
		  hs_y.Add(h_dy_y);
		  //THStack hs_n_ext_fromPV_3("hs_n_ext_fromPV_3","");
		  //hs_n_ext_fromPV_3.Add(h_elastic_x130_n_ext_fromPV_3);
		  //hs_n_ext_fromPV_3.Add(h_inel_el_x130_n_ext_fromPV_3);
		  //hs_n_ext_fromPV_3.Add(h_dy_n_ext_fromPV_3);
		  THStack hs_proton_xi_left_single("hs_proton_xi_left_single","Proton #xi Left Single;#xi(RP);Events");
		  hs_proton_xi_left_single.Add(h_elastic_x130_proton_xi_left_single);
		  hs_proton_xi_left_single.Add(h_inel_el_x130_proton_xi_left_single);
		  hs_proton_xi_left_single.Add(h_dy_proton_xi_left_single);
		  THStack hs_proton_xi_right_single("hs_proton_xi_right_single","Proton #xi Right Single;#xi(RP);Events");
		  hs_proton_xi_right_single.Add(h_elastic_x130_proton_xi_right_single);
		  hs_proton_xi_right_single.Add(h_inel_el_x130_proton_xi_right_single);
		  hs_proton_xi_right_single.Add(h_dy_proton_xi_right_single);
		  THStack hs_proton_xi_left_multi("hs_proton_xi_left_multi","Proton #xi Left Multi;#xi(RP);Events");
		  hs_proton_xi_left_multi.Add(h_elastic_x130_proton_xi_left_multi);
		  hs_proton_xi_left_multi.Add(h_inel_el_x130_proton_xi_left_multi);
		  hs_proton_xi_left_multi.Add(h_dy_proton_xi_left_multi);
		  THStack hs_proton_xi_right_multi("hs_proton_xi_right_multi","Proton #xi Right Multi;#xi(RP);Events");
		  hs_proton_xi_right_multi.Add(h_elastic_x130_proton_xi_right_multi);
		  hs_proton_xi_right_multi.Add(h_inel_el_x130_proton_xi_right_multi);
		  hs_proton_xi_right_multi.Add(h_dy_proton_xi_right_multi);
		  THStack hs_diff_proton_reco_pair_xi_left_single("hs_diff_proton_reco_pair_xi_left_single","reco (Proton - Pair) #xi Left Single;#xi(RP) - #xi({#mu^{+}#mu^{-}});Events");
		  hs_diff_proton_reco_pair_xi_left_single.Add(h_elastic_x130_diff_proton_reco_pair_xi_left_single);
		  hs_diff_proton_reco_pair_xi_left_single.Add(h_inel_el_x130_diff_proton_reco_pair_xi_left_single);
		  hs_diff_proton_reco_pair_xi_left_single.Add(h_dy_diff_proton_reco_pair_xi_left_single);
		  THStack hs_diff_proton_reco_pair_xi_right_single("hs_diff_proton_reco_pair_xi_right_single","reco (Proton - Pair) #xi Right Single;#xi(RP) - #xi({#mu^{+}#mu^{-}});Events");
		  hs_diff_proton_reco_pair_xi_right_single.Add(h_elastic_x130_diff_proton_reco_pair_xi_right_single);
		  hs_diff_proton_reco_pair_xi_right_single.Add(h_inel_el_x130_diff_proton_reco_pair_xi_right_single);
		  hs_diff_proton_reco_pair_xi_right_single.Add(h_dy_diff_proton_reco_pair_xi_right_single);
		  THStack hs_diff_proton_reco_pair_xi_left_multi("hs_diff_proton_reco_pair_xi_left_multi","reco (Proton - Pair) #xi Left Multi;#xi(RP) - #xi({#mu^{+}#mu^{-}});Events");
		  hs_diff_proton_reco_pair_xi_left_multi.Add(h_elastic_x130_diff_proton_reco_pair_xi_left_multi);
		  hs_diff_proton_reco_pair_xi_left_multi.Add(h_inel_el_x130_diff_proton_reco_pair_xi_left_multi);
		  hs_diff_proton_reco_pair_xi_left_multi.Add(h_dy_diff_proton_reco_pair_xi_left_multi);
		  THStack hs_diff_proton_reco_pair_xi_right_multi("hs_diff_proton_reco_pair_xi_right_multi","reco (Proton - Pair) #xi Right Multi;#xi(RP) - #xi({#mu^{+}#mu^{-}});Events");
		  hs_diff_proton_reco_pair_xi_right_multi.Add(h_elastic_x130_diff_proton_reco_pair_xi_right_multi);
		  hs_diff_proton_reco_pair_xi_right_multi.Add(h_inel_el_x130_diff_proton_reco_pair_xi_right_multi);
		  hs_diff_proton_reco_pair_xi_right_multi.Add(h_dy_diff_proton_reco_pair_xi_right_multi);
		  THStack hs_ratio_proton_reco_pair_xi_left_single("hs_ratio_proton_reco_pair_xi_left_single","reco (1 - Proton/Pair) #xi Left Single;1 - #xi(RP)/#xi({#mu^{+}#mu^{-}});Events");
		  hs_ratio_proton_reco_pair_xi_left_single.Add(h_elastic_x130_ratio_proton_reco_pair_xi_left_single);
		  hs_ratio_proton_reco_pair_xi_left_single.Add(h_inel_el_x130_ratio_proton_reco_pair_xi_left_single);
		  hs_ratio_proton_reco_pair_xi_left_single.Add(h_dy_ratio_proton_reco_pair_xi_left_single);
		  THStack hs_ratio_proton_reco_pair_xi_right_single("hs_ratio_proton_reco_pair_xi_right_single","reco (1 - Proton/Pair) #xi Right Single;1 - #xi(RP)/#xi({#mu^{+}#mu^{-}});Events");
		  hs_ratio_proton_reco_pair_xi_right_single.Add(h_elastic_x130_ratio_proton_reco_pair_xi_right_single);
		  hs_ratio_proton_reco_pair_xi_right_single.Add(h_inel_el_x130_ratio_proton_reco_pair_xi_right_single);
		  hs_ratio_proton_reco_pair_xi_right_single.Add(h_dy_ratio_proton_reco_pair_xi_right_single);
		  THStack hs_ratio_proton_reco_pair_xi_left_multi("hs_ratio_proton_reco_pair_xi_left_multi","reco (1 - Proton/Pair) #xi Left Multi;1 - #xi(RP)/#xi({#mu^{+}#mu^{-}});Events");
		  hs_ratio_proton_reco_pair_xi_left_multi.Add(h_elastic_x130_ratio_proton_reco_pair_xi_left_multi);
		  hs_ratio_proton_reco_pair_xi_left_multi.Add(h_inel_el_x130_ratio_proton_reco_pair_xi_left_multi);
		  hs_ratio_proton_reco_pair_xi_left_multi.Add(h_dy_ratio_proton_reco_pair_xi_left_multi);
		  THStack hs_ratio_proton_reco_pair_xi_right_multi("hs_ratio_proton_reco_pair_xi_right_multi","reco (1 - Proton/Pair) #xi Right Multi;1 - #xi(RP)/#xi({#mu^{+}#mu^{-}});Events");
		  hs_ratio_proton_reco_pair_xi_right_multi.Add(h_elastic_x130_ratio_proton_reco_pair_xi_right_multi);
		  hs_ratio_proton_reco_pair_xi_right_multi.Add(h_inel_el_x130_ratio_proton_reco_pair_xi_right_multi);
		  hs_ratio_proton_reco_pair_xi_right_multi.Add(h_dy_ratio_proton_reco_pair_xi_right_multi);
     
		  THStack hs_mass_re("hs_mass_re","#mu^{+}#mu^{-} Mass;M_{#mu^{+}#mu^{-}} (GeV/c^{2});Events");
		  hs_mass_re.Add(h_elastic_x130_mass);
		  hs_mass_re.Add(h_inel_el_x130_mass);
		  hs_mass_re.Add(h_dy_resample_mass);
		  THStack hs_pt_re("hs_pt_re","#mu^{+}#mu^{-} p_{T};p_{T #mu^{+}#mu^{-}} (GeV/c);Events");
		  hs_pt_re.Add(h_elastic_x130_pt);
		  hs_pt_re.Add(h_inel_el_x130_pt);
		  hs_pt_re.Add(h_dy_resample_pt);
		  THStack hs_y_re("hs_y_re","#mu^{+}#mu^{-} y;y_{#mu^{+}#mu^{-}};Events");
		  hs_y_re.Add(h_elastic_x130_y);
		  hs_y_re.Add(h_inel_el_x130_y);
		  hs_y_re.Add(h_dy_resample_y);
		  //THStack hs_n_ext_fromPV_3("hs_n_ext_fromPV_3","");
		  //hs_n_ext_fromPV_3.Add(h_elastic_x130_n_ext_fromPV_3);
		  //hs_n_ext_fromPV_3.Add(h_inel_el_x130_n_ext_fromPV_3);
		  //hs_n_ext_fromPV_3.Add(h_dy_resample_n_ext_fromPV_3);
		  THStack hs_proton_xi_left_single_re("hs_proton_xi_left_single_re","Proton #xi Left Single;#xi(RP);Events");
		  hs_proton_xi_left_single_re.Add(h_elastic_x130_proton_xi_left_single);
		  hs_proton_xi_left_single_re.Add(h_inel_el_x130_proton_xi_left_single);
		  hs_proton_xi_left_single_re.Add(h_dy_resample_proton_xi_left_single);
		  THStack hs_proton_xi_right_single_re("hs_proton_xi_right_single_re","Proton #xi Right Single;#xi(RP);Events");
		  hs_proton_xi_right_single_re.Add(h_elastic_x130_proton_xi_right_single);
		  hs_proton_xi_right_single_re.Add(h_inel_el_x130_proton_xi_right_single);
		  hs_proton_xi_right_single_re.Add(h_dy_resample_proton_xi_right_single);
		  THStack hs_proton_xi_left_multi_re("hs_proton_xi_left_multi_re","Proton #xi Left Multi;#xi(RP);Events");
		  hs_proton_xi_left_multi_re.Add(h_elastic_x130_proton_xi_left_multi);
		  hs_proton_xi_left_multi_re.Add(h_inel_el_x130_proton_xi_left_multi);
		  hs_proton_xi_left_multi_re.Add(h_dy_resample_proton_xi_left_multi);
		  THStack hs_proton_xi_right_multi_re("hs_proton_xi_right_multi_re","Proton #xi Right Multi;#xi(RP);Events");
		  hs_proton_xi_right_multi_re.Add(h_elastic_x130_proton_xi_right_multi);
		  hs_proton_xi_right_multi_re.Add(h_inel_el_x130_proton_xi_right_multi);
		  hs_proton_xi_right_multi_re.Add(h_dy_resample_proton_xi_right_multi);
		  THStack hs_diff_proton_reco_pair_xi_left_single_re("hs_diff_proton_reco_pair_xi_left_single_re","reco (Proton - Pair) #xi Left Single;#xi(RP) - #xi({#mu^{+}#mu^{-}});Events");
		  hs_diff_proton_reco_pair_xi_left_single_re.Add(h_elastic_x130_diff_proton_reco_pair_xi_left_single);
		  hs_diff_proton_reco_pair_xi_left_single_re.Add(h_inel_el_x130_diff_proton_reco_pair_xi_left_single);
		  hs_diff_proton_reco_pair_xi_left_single_re.Add(h_dy_resample_diff_proton_reco_pair_xi_left_single);
		  THStack hs_diff_proton_reco_pair_xi_right_single_re("hs_diff_proton_reco_pair_xi_right_single_re","reco (Proton - Pair) #xi Right Single;#xi(RP) - #xi({#mu^{+}#mu^{-}});Events");
		  hs_diff_proton_reco_pair_xi_right_single_re.Add(h_elastic_x130_diff_proton_reco_pair_xi_right_single);
		  hs_diff_proton_reco_pair_xi_right_single_re.Add(h_inel_el_x130_diff_proton_reco_pair_xi_right_single);
		  hs_diff_proton_reco_pair_xi_right_single_re.Add(h_dy_resample_diff_proton_reco_pair_xi_right_single);
		  THStack hs_diff_proton_reco_pair_xi_left_multi_re("hs_diff_proton_reco_pair_xi_left_multi_re","reco (Proton - Pair) #xi Left Multi;#xi(RP) - #xi({#mu^{+}#mu^{-}});Events");
		  hs_diff_proton_reco_pair_xi_left_multi_re.Add(h_elastic_x130_diff_proton_reco_pair_xi_left_multi);
		  hs_diff_proton_reco_pair_xi_left_multi_re.Add(h_inel_el_x130_diff_proton_reco_pair_xi_left_multi);
		  hs_diff_proton_reco_pair_xi_left_multi_re.Add(h_dy_resample_diff_proton_reco_pair_xi_left_multi);
		  THStack hs_diff_proton_reco_pair_xi_right_multi_re("hs_diff_proton_reco_pair_xi_right_multi_re","reco (Proton - Pair) #xi Right Multi;#xi(RP) - #xi({#mu^{+}#mu^{-}});Events");
		  hs_diff_proton_reco_pair_xi_right_multi_re.Add(h_elastic_x130_diff_proton_reco_pair_xi_right_multi);
		  hs_diff_proton_reco_pair_xi_right_multi_re.Add(h_inel_el_x130_diff_proton_reco_pair_xi_right_multi);
		  hs_diff_proton_reco_pair_xi_right_multi_re.Add(h_dy_resample_diff_proton_reco_pair_xi_right_multi);
		  THStack hs_ratio_proton_reco_pair_xi_left_single_re("hs_ratio_proton_reco_pair_xi_left_single_re","reco (1 - Proton/Pair) #xi Left Single;1 - #xi(RP)/#xi({#mu^{+}#mu^{-}});Events");
		  hs_ratio_proton_reco_pair_xi_left_single_re.Add(h_elastic_x130_ratio_proton_reco_pair_xi_left_single);
		  hs_ratio_proton_reco_pair_xi_left_single_re.Add(h_inel_el_x130_ratio_proton_reco_pair_xi_left_single);
		  hs_ratio_proton_reco_pair_xi_left_single_re.Add(h_dy_resample_ratio_proton_reco_pair_xi_left_single);
		  THStack hs_ratio_proton_reco_pair_xi_right_single_re("hs_ratio_proton_reco_pair_xi_right_single_re","reco (1 - Proton/Pair) #xi Right Single;1 - #xi(RP)/#xi({#mu^{+}#mu^{-}});Events");
		  hs_ratio_proton_reco_pair_xi_right_single_re.Add(h_elastic_x130_ratio_proton_reco_pair_xi_right_single);
		  hs_ratio_proton_reco_pair_xi_right_single_re.Add(h_inel_el_x130_ratio_proton_reco_pair_xi_right_single);
		  hs_ratio_proton_reco_pair_xi_right_single_re.Add(h_dy_resample_ratio_proton_reco_pair_xi_right_single);
		  THStack hs_ratio_proton_reco_pair_xi_left_multi_re("hs_ratio_proton_reco_pair_xi_left_multi_re","reco (1 - Proton/Pair) #xi Left Multi;1 - #xi(RP)/#xi({#mu^{+}#mu^{-}});Events");
		  hs_ratio_proton_reco_pair_xi_left_multi_re.Add(h_elastic_x130_ratio_proton_reco_pair_xi_left_multi);
		  hs_ratio_proton_reco_pair_xi_left_multi_re.Add(h_inel_el_x130_ratio_proton_reco_pair_xi_left_multi);
		  hs_ratio_proton_reco_pair_xi_left_multi_re.Add(h_dy_resample_ratio_proton_reco_pair_xi_left_multi);
		  THStack hs_ratio_proton_reco_pair_xi_right_multi_re("hs_ratio_proton_reco_pair_xi_right_multi_re","reco (1 - Proton/Pair) #xi Right Multi;1 - #xi(RP)/#xi({#mu^{+}#mu^{-}});Events");
		  hs_ratio_proton_reco_pair_xi_right_multi_re.Add(h_elastic_x130_ratio_proton_reco_pair_xi_right_multi);
		  hs_ratio_proton_reco_pair_xi_right_multi_re.Add(h_inel_el_x130_ratio_proton_reco_pair_xi_right_multi);
		  hs_ratio_proton_reco_pair_xi_right_multi_re.Add(h_dy_resample_ratio_proton_reco_pair_xi_right_multi);


		  THStack hs_clone_mass("hs_clone_mass","");
		  hs_clone_mass.Add(h_elastic_x130_clone_mass);
		  hs_clone_mass.Add(h_inel_el_x130_clone_mass);
		  hs_clone_mass.Add(h_dy_clone_mass);
		  THStack hs_clone_pt("hs_clone_pt","");
		  hs_clone_pt.Add(h_elastic_x130_clone_pt);
		  hs_clone_pt.Add(h_inel_el_x130_clone_pt);
		  hs_clone_pt.Add(h_dy_clone_pt);
		  THStack hs_clone_y("hs_clone_y","");
		  hs_clone_y.Add(h_elastic_x130_clone_y);
		  hs_clone_y.Add(h_inel_el_x130_clone_y);
		  hs_clone_y.Add(h_dy_clone_y);
		  

		  TCanvas *c_mass = new TCanvas("c_mass","",0,0,1200,1000);
		  hs_mass.Draw("HIST");
		  h_data_mass->Draw("SAME");
	 	  auto l_mass = new TLegend(0.9,0.9,0.7,0.7);
   	  l_mass->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_mass->AddEntry(h_data_mass,"Dados","lep");
		  l_mass->AddEntry((TObject*)0, "", "");
		  l_mass->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_mass->AddEntry((TObject*)0, "", "");
   	  l_mass->AddEntry(h_elastic_x130_mass,"Exclusivo","f");
   	  l_mass->AddEntry(h_inel_el_x130_mass,"Semi-exclusivo","f");
   	  l_mass->AddEntry(h_dy_mass,"Drell-Yan","f");
   	  l_mass->Draw();
		  c_mass->SaveAs("comp/mass.png");
		  c_mass->cd();
		  c_mass->Close();

		  TCanvas *c_pt = new TCanvas("c_pt","",0,0,1200,1000);
		  hs_pt.Draw("HIST");
		  h_data_pt->Draw("SAME");
	 	  auto l_pt = new TLegend(0.9,0.9,0.7,0.7);
   	  l_pt->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_pt->AddEntry(h_data_pt,"Dados","lep");
		  l_pt->AddEntry((TObject*)0, "", "");
		  l_pt->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_pt->AddEntry((TObject*)0, "", "");
   	  l_pt->AddEntry(h_elastic_x130_pt,"Exclusivo","f");
   	  l_pt->AddEntry(h_inel_el_x130_pt,"Semi-exclusivo","f");
   	  l_pt->AddEntry(h_dy_pt,"Drell-Yan","f");
   	  l_pt->Draw();
		  c_pt->SaveAs("comp/pt.png");
		  c_pt->cd();
		  c_pt->Close();

		  TCanvas *c_y = new TCanvas("c_y","",0,0,1200,1000);
		  hs_y.Draw("HIST");
		  h_data_y->Draw("SAME");
	 	  auto l_y = new TLegend(0.9,0.9,0.7,0.7);
   	  l_y->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_y->AddEntry(h_data_y,"Dados","lep");
		  l_y->AddEntry((TObject*)0, "", "");
		  l_y->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_y->AddEntry((TObject*)0, "", "");
   	  l_y->AddEntry(h_elastic_x130_y,"Exclusivo","f");
   	  l_y->AddEntry(h_inel_el_x130_y,"Semi-exclusivo","f");
   	  l_y->AddEntry(h_dy_y,"Drell-Yan","f");
   	  l_y->Draw();
		  c_y->SaveAs("comp/y.png");
		  c_y->cd();
		  c_y->Close();

		  //TCanvas *c_n_ext_fromPV_3 = new TCanvas("c_n_ext_fromPV_3","",0,0,1200,1000);
		  //hs_n_ext_fromPV_3.Draw("HIST");
		  //h_data_n_ext_fromPV_3->Draw("SAME");
		  //c_n_ext_fromPV_3->SaveAs("comp/n_ext_fromPV_3.png");
		  //c_n_ext_fromPV_3->cd();
		  //c_n_ext_fromPV_3->Close();

		  TCanvas *c_proton_xi_left_single = new TCanvas("c_proton_xi_left_single","",0,0,1200,1000);
		  hs_proton_xi_left_single.Draw("HIST");
		  h_data_proton_xi_left_single->Draw("SAME");
	 	  auto l_proton_xi_left_single = new TLegend(0.9,0.9,0.7,0.7);
   	  l_proton_xi_left_single->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_proton_xi_left_single->AddEntry(h_data_proton_xi_left_single,"Dados","lep");
		  l_proton_xi_left_single->AddEntry((TObject*)0, "", "");
		  l_proton_xi_left_single->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_proton_xi_left_single->AddEntry((TObject*)0, "", "");
   	  l_proton_xi_left_single->AddEntry(h_elastic_x130_proton_xi_left_single,"Exclusivo","f");
   	  l_proton_xi_left_single->AddEntry(h_inel_el_x130_proton_xi_left_single,"Semi-exclusivo","f");
   	  l_proton_xi_left_single->AddEntry(h_dy_proton_xi_left_single,"Drell-Yan","f");
   	  l_proton_xi_left_single->Draw();
		  c_proton_xi_left_single->SaveAs("comp/proton_xi_left_single.png");
		  c_proton_xi_left_single->cd();
		  c_proton_xi_left_single->Close();

		  TCanvas *c_proton_xi_right_single = new TCanvas("c_proton_xi_right_single","",0,0,1200,1000);
		  hs_proton_xi_right_single.Draw("HIST");
		  h_data_proton_xi_right_single->Draw("SAME");
	 	  auto l_proton_xi_right_single = new TLegend(0.9,0.9,0.7,0.7);
   	  l_proton_xi_right_single->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_proton_xi_right_single->AddEntry(h_data_proton_xi_right_single,"Dados","lep");
		  l_proton_xi_right_single->AddEntry((TObject*)0, "", "");
		  l_proton_xi_right_single->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_proton_xi_right_single->AddEntry((TObject*)0, "", "");
   	  l_proton_xi_right_single->AddEntry(h_elastic_x130_proton_xi_right_single,"Exclusivo","f");
   	  l_proton_xi_right_single->AddEntry(h_inel_el_x130_proton_xi_right_single,"Semi-exclusivo","f");
   	  l_proton_xi_right_single->AddEntry(h_dy_proton_xi_right_single,"Drell-Yan","f");
   	  l_proton_xi_right_single->Draw();
		  c_proton_xi_right_single->SaveAs("comp/proton_xi_right_single.png");
		  c_proton_xi_right_single->cd();
		  c_proton_xi_right_single->Close();

		  TCanvas *c_proton_xi_left_multi = new TCanvas("c_proton_xi_left_multi","",0,0,1200,1000);
		  hs_proton_xi_left_multi.Draw("HIST");
		  h_data_proton_xi_left_multi->Draw("SAME");
	 	  auto l_proton_xi_left_multi = new TLegend(0.9,0.9,0.7,0.7);
   	  l_proton_xi_left_multi->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_proton_xi_left_multi->AddEntry(h_data_proton_xi_left_multi,"Dados","lep");
		  l_proton_xi_left_multi->AddEntry((TObject*)0, "", "");
		  l_proton_xi_left_multi->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_proton_xi_left_multi->AddEntry((TObject*)0, "", "");
   	  l_proton_xi_left_multi->AddEntry(h_elastic_x130_proton_xi_left_multi,"Exclusivo","f");
   	  l_proton_xi_left_multi->AddEntry(h_inel_el_x130_proton_xi_left_multi,"Semi-exclusivo","f");
   	  l_proton_xi_left_multi->AddEntry(h_dy_proton_xi_left_multi,"Drell-Yan","f");
   	  l_proton_xi_left_multi->Draw();
		  c_proton_xi_left_multi->SaveAs("comp/proton_xi_left_multi.png");
		  c_proton_xi_left_multi->cd();
		  c_proton_xi_left_multi->Close();

		  TCanvas *c_proton_xi_right_multi = new TCanvas("c_proton_xi_right_multi","",0,0,1200,1000);
		  hs_proton_xi_right_multi.Draw("HIST");
		  h_data_proton_xi_right_multi->Draw("SAME");
	 	  auto l_proton_xi_right_multi = new TLegend(0.9,0.9,0.7,0.7);
   	  l_proton_xi_right_multi->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_proton_xi_right_multi->AddEntry(h_data_proton_xi_right_multi,"Dados","lep");
		  l_proton_xi_right_multi->AddEntry((TObject*)0, "", "");
		  l_proton_xi_right_multi->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_proton_xi_right_multi->AddEntry((TObject*)0, "", "");
   	  l_proton_xi_right_multi->AddEntry(h_elastic_x130_proton_xi_right_multi,"Exclusivo","f");
   	  l_proton_xi_right_multi->AddEntry(h_inel_el_x130_proton_xi_right_multi,"Semi-exclusivo","f");
   	  l_proton_xi_right_multi->AddEntry(h_dy_proton_xi_right_multi,"Drell-Yan","f");
   	  l_proton_xi_right_multi->Draw();
		  c_proton_xi_right_multi->SaveAs("comp/proton_xi_right_multi.png");
		  c_proton_xi_right_multi->cd();
		  c_proton_xi_right_multi->Close();

		  TCanvas *c_diff_proton_reco_pair_xi_left_single = new TCanvas("c_diff_proton_reco_pair_xi_left_single","",0,0,1200,1000);
		  hs_diff_proton_reco_pair_xi_left_single.Draw("HIST");
		  h_data_diff_proton_reco_pair_xi_left_single->Draw("SAME");
	 	  auto l_diff_proton_reco_pair_xi_left_single = new TLegend(0.9,0.9,0.7,0.7);
   	  l_diff_proton_reco_pair_xi_left_single->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_diff_proton_reco_pair_xi_left_single->AddEntry(h_data_diff_proton_reco_pair_xi_left_single,"Dados","lep");
		  l_diff_proton_reco_pair_xi_left_single->AddEntry((TObject*)0, "", "");
		  l_diff_proton_reco_pair_xi_left_single->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_diff_proton_reco_pair_xi_left_single->AddEntry((TObject*)0, "", "");
   	  l_diff_proton_reco_pair_xi_left_single->AddEntry(h_elastic_x130_diff_proton_reco_pair_xi_left_single,"Exclusivo","f");
   	  l_diff_proton_reco_pair_xi_left_single->AddEntry(h_inel_el_x130_diff_proton_reco_pair_xi_left_single,"Semi-exclusivo","f");
   	  l_diff_proton_reco_pair_xi_left_single->AddEntry(h_dy_diff_proton_reco_pair_xi_left_single,"Drell-Yan","f");
   	  l_diff_proton_reco_pair_xi_left_single->Draw();
		  c_diff_proton_reco_pair_xi_left_single->SaveAs("comp/diff_proton_reco_pair_xi_left_single.png");
		  c_diff_proton_reco_pair_xi_left_single->cd();
		  c_diff_proton_reco_pair_xi_left_single->Close();

		  TCanvas *c_diff_proton_reco_pair_xi_right_single = new TCanvas("c_diff_proton_reco_pair_xi_right_single","",0,0,1200,1000);
		  hs_diff_proton_reco_pair_xi_right_single.Draw("HIST");
		  h_data_diff_proton_reco_pair_xi_right_single->Draw("SAME");
	 	  auto l_diff_proton_reco_pair_xi_right_single = new TLegend(0.9,0.9,0.7,0.7);
   	  l_diff_proton_reco_pair_xi_right_single->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_diff_proton_reco_pair_xi_right_single->AddEntry(h_data_diff_proton_reco_pair_xi_right_single,"Dados","lep");
		  l_diff_proton_reco_pair_xi_right_single->AddEntry((TObject*)0, "", "");
		  l_diff_proton_reco_pair_xi_right_single->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_diff_proton_reco_pair_xi_right_single->AddEntry((TObject*)0, "", "");
   	  l_diff_proton_reco_pair_xi_right_single->AddEntry(h_elastic_x130_diff_proton_reco_pair_xi_right_single,"Exclusivo","f");
   	  l_diff_proton_reco_pair_xi_right_single->AddEntry(h_inel_el_x130_diff_proton_reco_pair_xi_right_single,"Semi-exclusivo","f");
   	  l_diff_proton_reco_pair_xi_right_single->AddEntry(h_dy_diff_proton_reco_pair_xi_right_single,"Drell-Yan","f");
   	  l_diff_proton_reco_pair_xi_right_single->Draw();
		  c_diff_proton_reco_pair_xi_right_single->SaveAs("comp/diff_proton_reco_pair_xi_right_single.png");
		  c_diff_proton_reco_pair_xi_right_single->cd();
		  c_diff_proton_reco_pair_xi_right_single->Close();

		  TCanvas *c_diff_proton_reco_pair_xi_left_multi = new TCanvas("c_diff_proton_reco_pair_xi_left_multi","",0,0,1200,1000);
		  hs_diff_proton_reco_pair_xi_left_multi.Draw("HIST");
		  h_data_diff_proton_reco_pair_xi_left_multi->Draw("SAME");
	 	  auto l_diff_proton_reco_pair_xi_left_multi = new TLegend(0.9,0.9,0.7,0.7);
   	  l_diff_proton_reco_pair_xi_left_multi->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_diff_proton_reco_pair_xi_left_multi->AddEntry(h_data_diff_proton_reco_pair_xi_left_multi,"Dados","lep");
		  l_diff_proton_reco_pair_xi_left_multi->AddEntry((TObject*)0, "", "");
		  l_diff_proton_reco_pair_xi_left_multi->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_diff_proton_reco_pair_xi_left_multi->AddEntry((TObject*)0, "", "");
   	  l_diff_proton_reco_pair_xi_left_multi->AddEntry(h_elastic_x130_diff_proton_reco_pair_xi_left_multi,"Exclusivo","f");
   	  l_diff_proton_reco_pair_xi_left_multi->AddEntry(h_inel_el_x130_diff_proton_reco_pair_xi_left_multi,"Semi-exclusivo","f");
   	  l_diff_proton_reco_pair_xi_left_multi->AddEntry(h_dy_diff_proton_reco_pair_xi_left_multi,"Drell-Yan","f");
   	  l_diff_proton_reco_pair_xi_left_multi->Draw();
		  c_diff_proton_reco_pair_xi_left_multi->SaveAs("comp/diff_proton_reco_pair_xi_left_multi.png");
		  c_diff_proton_reco_pair_xi_left_multi->cd();
		  c_diff_proton_reco_pair_xi_left_multi->Close();

		  TCanvas *c_diff_proton_reco_pair_xi_right_multi = new TCanvas("c_diff_proton_reco_pair_xi_right_multi","",0,0,1200,1000);
		  hs_diff_proton_reco_pair_xi_right_multi.Draw("HIST");
		  h_data_diff_proton_reco_pair_xi_right_multi->Draw("SAME");
	 	  auto l_diff_proton_reco_pair_xi_right_multi = new TLegend(0.9,0.9,0.7,0.7);
   	  l_diff_proton_reco_pair_xi_right_multi->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_diff_proton_reco_pair_xi_right_multi->AddEntry(h_data_diff_proton_reco_pair_xi_right_multi,"Dados","lep");
		  l_diff_proton_reco_pair_xi_right_multi->AddEntry((TObject*)0, "", "");
		  l_diff_proton_reco_pair_xi_right_multi->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_diff_proton_reco_pair_xi_right_multi->AddEntry((TObject*)0, "", "");
   	  l_diff_proton_reco_pair_xi_right_multi->AddEntry(h_elastic_x130_diff_proton_reco_pair_xi_right_multi,"Exclusivo","f");
   	  l_diff_proton_reco_pair_xi_right_multi->AddEntry(h_inel_el_x130_diff_proton_reco_pair_xi_right_multi,"Semi-exclusivo","f");
   	  l_diff_proton_reco_pair_xi_right_multi->AddEntry(h_dy_diff_proton_reco_pair_xi_right_multi,"Drell-Yan","f");
   	  l_diff_proton_reco_pair_xi_right_multi->Draw();
		  c_diff_proton_reco_pair_xi_right_multi->SaveAs("comp/diff_proton_reco_pair_xi_right_multi.png");
		  c_diff_proton_reco_pair_xi_right_multi->cd();
		  c_diff_proton_reco_pair_xi_right_multi->Close();

		  TCanvas *c_ratio_proton_reco_pair_xi_left_single = new TCanvas("c_ratio_proton_reco_pair_xi_left_single","",0,0,1200,1000);
		  hs_ratio_proton_reco_pair_xi_left_single.Draw("HIST");
		  h_data_ratio_proton_reco_pair_xi_left_single->Draw("SAME");
	 	  auto l_ratio_proton_reco_pair_xi_left_single = new TLegend(0.9,0.9,0.7,0.7);
   	  l_ratio_proton_reco_pair_xi_left_single->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_ratio_proton_reco_pair_xi_left_single->AddEntry(h_data_ratio_proton_reco_pair_xi_left_single,"Dados","lep");
		  l_ratio_proton_reco_pair_xi_left_single->AddEntry((TObject*)0, "", "");
		  l_ratio_proton_reco_pair_xi_left_single->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_ratio_proton_reco_pair_xi_left_single->AddEntry((TObject*)0, "", "");
   	  l_ratio_proton_reco_pair_xi_left_single->AddEntry(h_elastic_x130_ratio_proton_reco_pair_xi_left_single,"Exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_left_single->AddEntry(h_inel_el_x130_ratio_proton_reco_pair_xi_left_single,"Semi-exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_left_single->AddEntry(h_dy_ratio_proton_reco_pair_xi_left_single,"Drell-Yan","f");
   	  l_ratio_proton_reco_pair_xi_left_single->Draw();
		  c_ratio_proton_reco_pair_xi_left_single->SaveAs("comp/ratio_proton_reco_pair_xi_left_single.png");
		  c_ratio_proton_reco_pair_xi_left_single->cd();
		  c_ratio_proton_reco_pair_xi_left_single->Close();

		  TCanvas *c_ratio_proton_reco_pair_xi_right_single = new TCanvas("c_ratio_proton_reco_pair_xi_right_single","",0,0,1200,1000);
		  hs_ratio_proton_reco_pair_xi_right_single.Draw("HIST");
		  h_data_ratio_proton_reco_pair_xi_right_single->Draw("SAME");
	 	  auto l_ratio_proton_reco_pair_xi_right_single = new TLegend(0.9,0.9,0.7,0.7);
   	  l_ratio_proton_reco_pair_xi_right_single->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_ratio_proton_reco_pair_xi_right_single->AddEntry(h_data_ratio_proton_reco_pair_xi_right_single,"Dados","lep");
		  l_ratio_proton_reco_pair_xi_right_single->AddEntry((TObject*)0, "", "");
		  l_ratio_proton_reco_pair_xi_right_single->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_ratio_proton_reco_pair_xi_right_single->AddEntry((TObject*)0, "", "");
   	  l_ratio_proton_reco_pair_xi_right_single->AddEntry(h_elastic_x130_ratio_proton_reco_pair_xi_right_single,"Exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_right_single->AddEntry(h_inel_el_x130_ratio_proton_reco_pair_xi_right_single,"Semi-exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_right_single->AddEntry(h_dy_ratio_proton_reco_pair_xi_right_single,"Drell-Yan","f");
   	  l_ratio_proton_reco_pair_xi_right_single->Draw();
		  c_ratio_proton_reco_pair_xi_right_single->SaveAs("comp/ratio_proton_reco_pair_xi_right_single.png");
		  c_ratio_proton_reco_pair_xi_right_single->cd();
		  c_ratio_proton_reco_pair_xi_right_single->Close();

		  TCanvas *c_ratio_proton_reco_pair_xi_left_multi = new TCanvas("c_ratio_proton_reco_pair_xi_left_multi","",0,0,1200,1000);
		  hs_ratio_proton_reco_pair_xi_left_multi.Draw("HIST");
		  h_data_ratio_proton_reco_pair_xi_left_multi->Draw("SAME");
	 	  auto l_ratio_proton_reco_pair_xi_left_multi = new TLegend(0.9,0.9,0.7,0.7);
   	  l_ratio_proton_reco_pair_xi_left_multi->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_ratio_proton_reco_pair_xi_left_multi->AddEntry(h_data_ratio_proton_reco_pair_xi_left_multi,"Dados","lep");
		  l_ratio_proton_reco_pair_xi_left_multi->AddEntry((TObject*)0, "", "");
		  l_ratio_proton_reco_pair_xi_left_multi->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_ratio_proton_reco_pair_xi_left_multi->AddEntry((TObject*)0, "", "");
   	  l_ratio_proton_reco_pair_xi_left_multi->AddEntry(h_elastic_x130_ratio_proton_reco_pair_xi_left_multi,"Exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_left_multi->AddEntry(h_inel_el_x130_ratio_proton_reco_pair_xi_left_multi,"Semi-exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_left_multi->AddEntry(h_dy_ratio_proton_reco_pair_xi_left_multi,"Drell-Yan","f");
   	  l_ratio_proton_reco_pair_xi_left_multi->Draw();
		  c_ratio_proton_reco_pair_xi_left_multi->SaveAs("comp/ratio_proton_reco_pair_xi_left_multi.png");
		  c_ratio_proton_reco_pair_xi_left_multi->cd();
		  c_ratio_proton_reco_pair_xi_left_multi->Close();

		  TCanvas *c_ratio_proton_reco_pair_xi_right_multi = new TCanvas("c_ratio_proton_reco_pair_xi_right_multi","",0,0,1200,1000);
		  hs_ratio_proton_reco_pair_xi_right_multi.Draw("HIST");
		  h_data_ratio_proton_reco_pair_xi_right_multi->Draw("SAME");
	 	  auto l_ratio_proton_reco_pair_xi_right_multi = new TLegend(0.9,0.9,0.7,0.7);
   	  l_ratio_proton_reco_pair_xi_right_multi->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_ratio_proton_reco_pair_xi_right_multi->AddEntry(h_data_ratio_proton_reco_pair_xi_right_multi,"Dados","lep");
		  l_ratio_proton_reco_pair_xi_right_multi->AddEntry((TObject*)0, "", "");
		  l_ratio_proton_reco_pair_xi_right_multi->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_ratio_proton_reco_pair_xi_right_multi->AddEntry((TObject*)0, "", "");
   	  l_ratio_proton_reco_pair_xi_right_multi->AddEntry(h_elastic_x130_ratio_proton_reco_pair_xi_right_multi,"Exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_right_multi->AddEntry(h_inel_el_x130_ratio_proton_reco_pair_xi_right_multi,"Semi-exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_right_multi->AddEntry(h_dy_ratio_proton_reco_pair_xi_right_multi,"Drell-Yan","f");
   	  l_ratio_proton_reco_pair_xi_right_multi->Draw();
		  c_ratio_proton_reco_pair_xi_right_multi->SaveAs("comp/ratio_proton_reco_pair_xi_right_multi.png");
		  c_ratio_proton_reco_pair_xi_right_multi->cd();
		  c_ratio_proton_reco_pair_xi_right_multi->Close();

		  TCanvas *c_mass_re = new TCanvas("c_mass_re","",0,0,1200,1000);
		  hs_mass_re.Draw("HIST");
		  h_data_mass->Draw("SAME");
	 	  auto l_mass_re = new TLegend(0.9,0.9,0.7,0.7);
   	  l_mass_re->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_mass_re->AddEntry(h_data_mass,"Dados","lep");
		  l_mass_re->AddEntry((TObject*)0, "", "");
		  l_mass_re->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_mass_re->AddEntry((TObject*)0, "", "");
   	  l_mass_re->AddEntry(h_elastic_x130_mass,"Exclusivo","f");
   	  l_mass_re->AddEntry(h_inel_el_x130_mass,"Semi-exclusivo","f");
   	  l_mass_re->AddEntry(h_dy_resample_mass,"Drell-Yan","f");
   	  l_mass_re->Draw();
		  c_mass_re->SaveAs("comp/mass_resample.png");
		  c_mass_re->cd();
		  c_mass_re->Close();

		  TCanvas *c_pt_re = new TCanvas("c_pt_re","",0,0,1200,1000);
		  hs_pt_re.Draw("HIST");
		  h_data_pt->Draw("SAME");
	 	  auto l_pt_re = new TLegend(0.9,0.9,0.7,0.7);
   	  l_pt_re->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_pt_re->AddEntry(h_data_pt,"Dados","lep");
		  l_pt_re->AddEntry((TObject*)0, "", "");
		  l_pt_re->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_pt_re->AddEntry((TObject*)0, "", "");
   	  l_pt_re->AddEntry(h_elastic_x130_pt,"Exclusivo","f");
   	  l_pt_re->AddEntry(h_inel_el_x130_pt,"Semi-exclusivo","f");
   	  l_pt_re->AddEntry(h_dy_resample_pt,"Drell-Yan","f");
   	  l_pt_re->Draw();
		  c_pt_re->SaveAs("comp/pt_resample.png");
		  c_pt_re->cd();
		  c_pt_re->Close();

		  TCanvas *c_y_re = new TCanvas("c_y_re","",0,0,1200,1000);
		  hs_y_re.Draw("HIST");
		  h_data_y->Draw("SAME");
	 	  auto l_y_re = new TLegend(0.9,0.9,0.7,0.7);
   	  l_y_re->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_y_re->AddEntry(h_data_y,"Dados","lep");
		  l_y_re->AddEntry((TObject*)0, "", "");
		  l_y_re->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_y_re->AddEntry((TObject*)0, "", "");
   	  l_y_re->AddEntry(h_elastic_x130_y,"Exclusivo","f");
   	  l_y_re->AddEntry(h_inel_el_x130_y,"Semi-exclusivo","f");
   	  l_y_re->AddEntry(h_dy_resample_y,"Drell-Yan","f");
   	  l_y_re->Draw();
		  c_y_re->SaveAs("comp/y_resample.png");
		  c_y_re->cd();
		  c_y_re->Close();

		  //TCanvas *c_n_ext_fromPV_3 = new TCanvas("c_n_ext_fromPV_3","",0,0,1200,1000);
		  //hs_n_ext_fromPV_3.Draw("HIST");
		  //h_data_n_ext_fromPV_3->Draw("SAME");
		  //c_n_ext_fromPV_3->SaveAs("comp/n_ext_fromPV_3.png");
		  //c_n_ext_fromPV_3->cd();
		  //c_n_ext_fromPV_3->Close();

		  TCanvas *c_proton_xi_left_single_re = new TCanvas("c_proton_xi_left_single_re","",0,0,1200,1000);
		  hs_proton_xi_left_single_re.Draw("HIST");
		  h_data_proton_xi_left_single->Draw("SAME");
	 	  auto l_proton_xi_left_single_re = new TLegend(0.9,0.9,0.7,0.7);
   	  l_proton_xi_left_single_re->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_proton_xi_left_single_re->AddEntry(h_data_proton_xi_left_single,"Dados","lep");
		  l_proton_xi_left_single_re->AddEntry((TObject*)0, "", "");
		  l_proton_xi_left_single_re->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_proton_xi_left_single_re->AddEntry((TObject*)0, "", "");
   	  l_proton_xi_left_single_re->AddEntry(h_elastic_x130_proton_xi_left_single,"Exclusivo","f");
   	  l_proton_xi_left_single_re->AddEntry(h_inel_el_x130_proton_xi_left_single,"Semi-exclusivo","f");
   	  l_proton_xi_left_single_re->AddEntry(h_dy_resample_proton_xi_left_single,"Drell-Yan","f");
   	  l_proton_xi_left_single_re->Draw();
		  c_proton_xi_left_single_re->SaveAs("comp/proton_xi_left_single_resample.png");
		  c_proton_xi_left_single_re->cd();
		  c_proton_xi_left_single_re->Close();

		  TCanvas *c_proton_xi_right_single_re = new TCanvas("c_proton_xi_right_single","",0,0,1200,1000);
		  hs_proton_xi_right_single_re.Draw("HIST");
		  h_data_proton_xi_right_single->Draw("SAME");
	 	  auto l_proton_xi_right_single_re = new TLegend(0.9,0.9,0.7,0.7);
   	  l_proton_xi_right_single_re->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_proton_xi_right_single_re->AddEntry(h_data_proton_xi_right_single,"Dados","lep");
		  l_proton_xi_right_single_re->AddEntry((TObject*)0, "", "");
		  l_proton_xi_right_single_re->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_proton_xi_right_single_re->AddEntry((TObject*)0, "", "");
   	  l_proton_xi_right_single_re->AddEntry(h_elastic_x130_proton_xi_right_single,"Exclusivo","f");
   	  l_proton_xi_right_single_re->AddEntry(h_inel_el_x130_proton_xi_right_single,"Semi-exclusivo","f");
   	  l_proton_xi_right_single_re->AddEntry(h_dy_proton_xi_right_single,"Drell-Yan","f");
   	  l_proton_xi_right_single_re->Draw();
		  c_proton_xi_right_single_re->SaveAs("comp/proton_xi_right_single.png");
		  c_proton_xi_right_single_re->cd();
		  c_proton_xi_right_single_re->Close();

		  TCanvas *c_proton_xi_left_multi_re = new TCanvas("c_proton_xi_left_multi_re","",0,0,1200,1000);
		  hs_proton_xi_left_multi_re.Draw("HIST");
		  h_data_proton_xi_left_multi->Draw("SAME");
	 	  auto l_proton_xi_left_multi_re = new TLegend(0.9,0.9,0.7,0.7);
   	  l_proton_xi_left_multi_re->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_proton_xi_left_multi_re->AddEntry(h_data_proton_xi_left_multi,"Dados","lep");
		  l_proton_xi_left_multi_re->AddEntry((TObject*)0, "", "");
		  l_proton_xi_left_multi_re->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_proton_xi_left_multi_re->AddEntry((TObject*)0, "", "");
   	  l_proton_xi_left_multi_re->AddEntry(h_elastic_x130_proton_xi_left_multi,"Exclusivo","f");
   	  l_proton_xi_left_multi_re->AddEntry(h_inel_el_x130_proton_xi_left_multi,"Semi-exclusivo","f");
   	  l_proton_xi_left_multi_re->AddEntry(h_dy_resample_proton_xi_left_multi,"Drell-Yan","f");
   	  l_proton_xi_left_multi_re->Draw();
		  c_proton_xi_left_multi_re->SaveAs("comp/proton_xi_left_multi_resample.png");
		  c_proton_xi_left_multi_re->cd();
		  c_proton_xi_left_multi_re->Close();

		  TCanvas *c_proton_xi_right_multi_re = new TCanvas("c_proton_xi_right_multi_re","",0,0,1200,1000);
		  hs_proton_xi_right_multi_re.Draw("HIST");
		  h_data_proton_xi_right_multi->Draw("SAME");
	 	  auto l_proton_xi_right_multi_re = new TLegend(0.9,0.9,0.7,0.7);
   	  l_proton_xi_right_multi_re->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_proton_xi_right_multi_re->AddEntry(h_data_proton_xi_right_multi,"Dados","lep");
		  l_proton_xi_right_multi_re->AddEntry((TObject*)0, "", "");
		  l_proton_xi_right_multi_re->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_proton_xi_right_multi_re->AddEntry((TObject*)0, "", "");
   	  l_proton_xi_right_multi_re->AddEntry(h_elastic_x130_proton_xi_right_multi,"Exclusivo","f");
   	  l_proton_xi_right_multi_re->AddEntry(h_inel_el_x130_proton_xi_right_multi,"Semi-exclusivo","f");
   	  l_proton_xi_right_multi_re->AddEntry(h_dy_resample_proton_xi_right_multi,"Drell-Yan","f");
   	  l_proton_xi_right_multi_re->Draw();
		  c_proton_xi_right_multi_re->SaveAs("comp/proton_xi_right_multi_resample.png");
		  c_proton_xi_right_multi_re->cd();
		  c_proton_xi_right_multi_re->Close();

		  TCanvas *c_diff_proton_reco_pair_xi_left_single_re = new TCanvas("c_diff_proton_reco_pair_xi_left_single_re","",0,0,1200,1000);
		  hs_diff_proton_reco_pair_xi_left_single_re.Draw("HIST");
		  h_data_diff_proton_reco_pair_xi_left_single->Draw("SAME");
	 	  auto l_diff_proton_reco_pair_xi_left_single_re = new TLegend(0.9,0.9,0.7,0.7);
   	  l_diff_proton_reco_pair_xi_left_single_re->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_diff_proton_reco_pair_xi_left_single_re->AddEntry(h_data_diff_proton_reco_pair_xi_left_single,"Dados","lep");
		  l_diff_proton_reco_pair_xi_left_single_re->AddEntry((TObject*)0, "", "");
		  l_diff_proton_reco_pair_xi_left_single_re->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_diff_proton_reco_pair_xi_left_single_re->AddEntry((TObject*)0, "", "");
   	  l_diff_proton_reco_pair_xi_left_single_re->AddEntry(h_elastic_x130_diff_proton_reco_pair_xi_left_single,"Exclusivo","f");
   	  l_diff_proton_reco_pair_xi_left_single_re->AddEntry(h_inel_el_x130_diff_proton_reco_pair_xi_left_single,"Semi-exclusivo","f");
   	  l_diff_proton_reco_pair_xi_left_single_re->AddEntry(h_dy_resample_diff_proton_reco_pair_xi_left_single,"Drell-Yan","f");
   	  l_diff_proton_reco_pair_xi_left_single_re->Draw();
		  c_diff_proton_reco_pair_xi_left_single_re->SaveAs("comp/diff_proton_reco_pair_xi_left_single_resample.png");
		  c_diff_proton_reco_pair_xi_left_single_re->cd();
		  c_diff_proton_reco_pair_xi_left_single_re->Close();

		  TCanvas *c_diff_proton_reco_pair_xi_right_single_re = new TCanvas("c_diff_proton_reco_pair_xi_right_single_re","",0,0,1200,1000);
		  hs_diff_proton_reco_pair_xi_right_single_re.Draw("HIST");
		  h_data_diff_proton_reco_pair_xi_right_single->Draw("SAME");
	 	  auto l_diff_proton_reco_pair_xi_right_single_re = new TLegend(0.9,0.9,0.7,0.7);
   	  l_diff_proton_reco_pair_xi_right_single_re->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_diff_proton_reco_pair_xi_right_single_re->AddEntry(h_data_diff_proton_reco_pair_xi_right_single,"Dados","lep");
		  l_diff_proton_reco_pair_xi_right_single_re->AddEntry((TObject*)0, "", "");
		  l_diff_proton_reco_pair_xi_right_single_re->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_diff_proton_reco_pair_xi_right_single_re->AddEntry((TObject*)0, "", "");
   	  l_diff_proton_reco_pair_xi_right_single_re->AddEntry(h_elastic_x130_diff_proton_reco_pair_xi_right_single,"Exclusivo","f");
   	  l_diff_proton_reco_pair_xi_right_single_re->AddEntry(h_inel_el_x130_diff_proton_reco_pair_xi_right_single,"Semi-exclusivo","f");
   	  l_diff_proton_reco_pair_xi_right_single_re->AddEntry(h_dy_resample_diff_proton_reco_pair_xi_right_single,"Drell-Yan","f");
   	  l_diff_proton_reco_pair_xi_right_single_re->Draw();
		  c_diff_proton_reco_pair_xi_right_single_re->SaveAs("comp/diff_proton_reco_pair_xi_right_single_resample.png");
		  c_diff_proton_reco_pair_xi_right_single_re->cd();
		  c_diff_proton_reco_pair_xi_right_single_re->Close();

		  TCanvas *c_diff_proton_reco_pair_xi_left_multi_re = new TCanvas("c_diff_proton_reco_pair_xi_left_multi_re","",0,0,1200,1000);
		  hs_diff_proton_reco_pair_xi_left_multi_re.Draw("HIST");
		  h_data_diff_proton_reco_pair_xi_left_multi->Draw("SAME");
	 	  auto l_diff_proton_reco_pair_xi_left_multi_re = new TLegend(0.9,0.9,0.7,0.7);
   	  l_diff_proton_reco_pair_xi_left_multi_re->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_diff_proton_reco_pair_xi_left_multi_re->AddEntry(h_data_diff_proton_reco_pair_xi_left_multi,"Dados","lep");
		  l_diff_proton_reco_pair_xi_left_multi_re->AddEntry((TObject*)0, "", "");
		  l_diff_proton_reco_pair_xi_left_multi_re->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_diff_proton_reco_pair_xi_left_multi_re->AddEntry((TObject*)0, "", "");
   	  l_diff_proton_reco_pair_xi_left_multi_re->AddEntry(h_elastic_x130_diff_proton_reco_pair_xi_left_multi,"Exclusivo","f");
   	  l_diff_proton_reco_pair_xi_left_multi_re->AddEntry(h_inel_el_x130_diff_proton_reco_pair_xi_left_multi,"Semi-exclusivo","f");
   	  l_diff_proton_reco_pair_xi_left_multi_re->AddEntry(h_dy_resample_diff_proton_reco_pair_xi_left_multi,"Drell-Yan","f");
   	  l_diff_proton_reco_pair_xi_left_multi_re->Draw();
		  c_diff_proton_reco_pair_xi_left_multi_re->SaveAs("comp/diff_proton_reco_pair_xi_left_multi_resample.png");
		  c_diff_proton_reco_pair_xi_left_multi_re->cd();
		  c_diff_proton_reco_pair_xi_left_multi_re->Close();

		  TCanvas *c_diff_proton_reco_pair_xi_right_multi_re = new TCanvas("c_diff_proton_reco_pair_xi_right_multi_re","",0,0,1200,1000);
		  hs_diff_proton_reco_pair_xi_right_multi_re.Draw("HIST");
		  h_data_diff_proton_reco_pair_xi_right_multi->Draw("SAME");
	 	  auto l_diff_proton_reco_pair_xi_right_multi_re = new TLegend(0.9,0.9,0.7,0.7);
   	  l_diff_proton_reco_pair_xi_right_multi_re->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_diff_proton_reco_pair_xi_right_multi_re->AddEntry(h_data_diff_proton_reco_pair_xi_right_multi,"Dados","lep");
		  l_diff_proton_reco_pair_xi_right_multi_re->AddEntry((TObject*)0, "", "");
		  l_diff_proton_reco_pair_xi_right_multi_re->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_diff_proton_reco_pair_xi_right_multi_re->AddEntry((TObject*)0, "", "");
   	  l_diff_proton_reco_pair_xi_right_multi_re->AddEntry(h_elastic_x130_diff_proton_reco_pair_xi_right_multi,"Exclusivo","f");
   	  l_diff_proton_reco_pair_xi_right_multi_re->AddEntry(h_inel_el_x130_diff_proton_reco_pair_xi_right_multi,"Semi-exclusivo","f");
   	  l_diff_proton_reco_pair_xi_right_multi_re->AddEntry(h_dy_resample_diff_proton_reco_pair_xi_right_multi,"Drell-Yan","f");
   	  l_diff_proton_reco_pair_xi_right_multi_re->Draw();
		  c_diff_proton_reco_pair_xi_right_multi_re->SaveAs("comp/diff_proton_reco_pair_xi_right_multi_resample.png");
		  c_diff_proton_reco_pair_xi_right_multi_re->cd();
		  c_diff_proton_reco_pair_xi_right_multi_re->Close();

		  TCanvas *c_ratio_proton_reco_pair_xi_left_single_re = new TCanvas("c_ratio_proton_reco_pair_xi_left_single_re","",0,0,1200,1000);
		  hs_ratio_proton_reco_pair_xi_left_single_re.Draw("HIST");
		  h_data_ratio_proton_reco_pair_xi_left_single->Draw("SAME");
	 	  auto l_ratio_proton_reco_pair_xi_left_single_re = new TLegend(0.9,0.9,0.7,0.7);
   	  l_ratio_proton_reco_pair_xi_left_single_re->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_ratio_proton_reco_pair_xi_left_single_re->AddEntry(h_data_ratio_proton_reco_pair_xi_left_single,"Dados","lep");
		  l_ratio_proton_reco_pair_xi_left_single_re->AddEntry((TObject*)0, "", "");
		  l_ratio_proton_reco_pair_xi_left_single_re->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_ratio_proton_reco_pair_xi_left_single_re->AddEntry((TObject*)0, "", "");
   	  l_ratio_proton_reco_pair_xi_left_single_re->AddEntry(h_elastic_x130_ratio_proton_reco_pair_xi_left_single,"Exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_left_single_re->AddEntry(h_inel_el_x130_ratio_proton_reco_pair_xi_left_single,"Semi-exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_left_single_re->AddEntry(h_dy_resample_ratio_proton_reco_pair_xi_left_single,"Drell-Yan","f");
   	  l_ratio_proton_reco_pair_xi_left_single_re->Draw();
		  c_ratio_proton_reco_pair_xi_left_single_re->SaveAs("comp/ratio_proton_reco_pair_xi_left_single_resample.png");
		  c_ratio_proton_reco_pair_xi_left_single_re->cd();
		  c_ratio_proton_reco_pair_xi_left_single_re->Close();

		  TCanvas *c_ratio_proton_reco_pair_xi_right_single_re = new TCanvas("c_ratio_proton_reco_pair_xi_right_single_re","",0,0,1200,1000);
		  hs_ratio_proton_reco_pair_xi_right_single_re.Draw("HIST");
		  h_data_ratio_proton_reco_pair_xi_right_single->Draw("SAME");
	 	  auto l_ratio_proton_reco_pair_xi_right_single_re = new TLegend(0.9,0.9,0.7,0.7);
   	  l_ratio_proton_reco_pair_xi_right_single_re->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_ratio_proton_reco_pair_xi_right_single_re->AddEntry(h_data_ratio_proton_reco_pair_xi_right_single,"Dados","lep");
		  l_ratio_proton_reco_pair_xi_right_single_re->AddEntry((TObject*)0, "", "");
		  l_ratio_proton_reco_pair_xi_right_single_re->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_ratio_proton_reco_pair_xi_right_single_re->AddEntry((TObject*)0, "", "");
   	  l_ratio_proton_reco_pair_xi_right_single_re->AddEntry(h_elastic_x130_ratio_proton_reco_pair_xi_right_single,"Exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_right_single_re->AddEntry(h_inel_el_x130_ratio_proton_reco_pair_xi_right_single,"Semi-exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_right_single_re->AddEntry(h_dy_resample_ratio_proton_reco_pair_xi_right_single,"Drell-Yan","f");
   	  l_ratio_proton_reco_pair_xi_right_single_re->Draw();
		  c_ratio_proton_reco_pair_xi_right_single_re->SaveAs("comp/ratio_proton_reco_pair_xi_right_single_resample.png");
		  c_ratio_proton_reco_pair_xi_right_single_re->cd();
		  c_ratio_proton_reco_pair_xi_right_single_re->Close();

		  TCanvas *c_ratio_proton_reco_pair_xi_left_multi_re = new TCanvas("c_ratio_proton_reco_pair_xi_left_multi_re","",0,0,1200,1000);
		  hs_ratio_proton_reco_pair_xi_left_multi_re.Draw("HIST");
		  h_data_ratio_proton_reco_pair_xi_left_multi->Draw("SAME");
	 	  auto l_ratio_proton_reco_pair_xi_left_multi_re = new TLegend(0.9,0.9,0.7,0.7);
   	  l_ratio_proton_reco_pair_xi_left_multi_re->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_ratio_proton_reco_pair_xi_left_multi_re->AddEntry(h_data_ratio_proton_reco_pair_xi_left_multi,"Dados","lep");
		  l_ratio_proton_reco_pair_xi_left_multi_re->AddEntry((TObject*)0, "", "");
		  l_ratio_proton_reco_pair_xi_left_multi_re->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_ratio_proton_reco_pair_xi_left_multi_re->AddEntry((TObject*)0, "", "");
   	  l_ratio_proton_reco_pair_xi_left_multi_re->AddEntry(h_elastic_x130_ratio_proton_reco_pair_xi_left_multi,"Exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_left_multi_re->AddEntry(h_inel_el_x130_ratio_proton_reco_pair_xi_left_multi,"Semi-exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_left_multi_re->AddEntry(h_dy_resample_ratio_proton_reco_pair_xi_left_multi,"Drell-Yan","f");
   	  l_ratio_proton_reco_pair_xi_left_multi_re->Draw();
		  c_ratio_proton_reco_pair_xi_left_multi_re->SaveAs("comp/ratio_proton_reco_pair_xi_left_multi_resample.png");
		  c_ratio_proton_reco_pair_xi_left_multi_re->cd();
		  c_ratio_proton_reco_pair_xi_left_multi_re->Close();

		  TCanvas *c_ratio_proton_reco_pair_xi_right_multi_re = new TCanvas("c_ratio_proton_reco_pair_xi_right_multi_re","",0,0,1200,1000);
		  hs_ratio_proton_reco_pair_xi_right_multi_re.Draw("HIST");
		  h_data_ratio_proton_reco_pair_xi_right_multi->Draw("SAME");
	 	  auto l_ratio_proton_reco_pair_xi_right_multi_re = new TLegend(0.9,0.9,0.7,0.7);
   	  l_ratio_proton_reco_pair_xi_right_multi_re->SetHeader("Work in progress","C"); // option "C" allows to center the header
   	  l_ratio_proton_reco_pair_xi_right_multi_re->AddEntry(h_data_ratio_proton_reco_pair_xi_right_multi,"Dados","lep");
		  l_ratio_proton_reco_pair_xi_right_multi_re->AddEntry((TObject*)0, "", "");
		  l_ratio_proton_reco_pair_xi_right_multi_re->AddEntry((TObject*)0, "Monte Carlo", "");
		  l_ratio_proton_reco_pair_xi_right_multi_re->AddEntry((TObject*)0, "", "");
   	  l_ratio_proton_reco_pair_xi_right_multi_re->AddEntry(h_elastic_x130_ratio_proton_reco_pair_xi_right_multi,"Exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_right_multi_re->AddEntry(h_inel_el_x130_ratio_proton_reco_pair_xi_right_multi,"Semi-exclusivo","f");
   	  l_ratio_proton_reco_pair_xi_right_multi_re->AddEntry(h_dy_resample_ratio_proton_reco_pair_xi_right_multi,"Drell-Yan","f");
   	  l_ratio_proton_reco_pair_xi_right_multi_re->Draw();
		  c_ratio_proton_reco_pair_xi_right_multi_re->SaveAs("comp/ratio_proton_reco_pair_xi_right_multi_resample.png");
		  c_ratio_proton_reco_pair_xi_right_multi_re->cd();
		  c_ratio_proton_reco_pair_xi_right_multi_re->Close();

		  TFile* f4 = new TFile("comp/comp_data_MC_2017.root", "RECREATE");
		  hs_mass.Draw("HIST");
		  hs_pt.Draw("HIST");
		  hs_y.Draw("HIST");
		  //hs_n_ext_fromPV_3.Draw("HIST");
		  hs_proton_xi_left_single.Draw("HIST");
		  hs_proton_xi_right_single.Draw("HIST");
		  hs_proton_xi_left_multi.Draw("HIST");
		  hs_proton_xi_right_multi.Draw("HIST");
		  hs_diff_proton_reco_pair_xi_left_single.Draw("HIST");
		  hs_diff_proton_reco_pair_xi_right_single.Draw("HIST");
		  hs_diff_proton_reco_pair_xi_left_multi.Draw("HIST");
		  hs_diff_proton_reco_pair_xi_right_multi.Draw("HIST");
		  hs_ratio_proton_reco_pair_xi_left_single.Draw("HIST");
		  hs_ratio_proton_reco_pair_xi_right_single.Draw("HIST");
		  hs_ratio_proton_reco_pair_xi_left_multi.Draw("HIST");
		  hs_ratio_proton_reco_pair_xi_right_multi.Draw("HIST");
		  hs_mass_re.Draw("HIST");
		  hs_pt_re.Draw("HIST");
		  hs_y_re.Draw("HIST");
		  //hs_n_ext_fromPV_3_re.Draw("HIST");
		  hs_proton_xi_left_single_re.Draw("HIST");
		  hs_proton_xi_right_single_re.Draw("HIST");
		  hs_proton_xi_left_multi_re.Draw("HIST");
		  hs_proton_xi_right_multi_re.Draw("HIST");
		  hs_diff_proton_reco_pair_xi_left_single_re.Draw("HIST");
		  hs_diff_proton_reco_pair_xi_right_single_re.Draw("HIST");
		  hs_diff_proton_reco_pair_xi_left_multi_re.Draw("HIST");
		  hs_diff_proton_reco_pair_xi_right_multi_re.Draw("HIST");
		  hs_ratio_proton_reco_pair_xi_left_single_re.Draw("HIST");
		  hs_ratio_proton_reco_pair_xi_right_single_re.Draw("HIST");
		  hs_ratio_proton_reco_pair_xi_left_multi_re.Draw("HIST");
		  hs_ratio_proton_reco_pair_xi_right_multi_re.Draw("HIST");
		  hs_clone_mass.Draw("HIST");
		  hs_clone_pt.Draw("HIST");
		  hs_clone_y.Draw("HIST");

		  h_data_mass->Draw("SAME");
		  h_data_pt->Draw("SAME");
		  h_data_y->Draw("SAME");
		  //h_data_n_ext_fromPV_3->Draw("SAME");
		  h_data_proton_xi_left_single->Draw("SAME");
		  h_data_proton_xi_right_single->Draw("SAME");
		  h_data_proton_xi_left_multi->Draw("SAME");
		  h_data_proton_xi_right_multi->Draw("SAME");
		  h_data_diff_proton_reco_pair_xi_left_single->Draw("SAME");
		  h_data_diff_proton_reco_pair_xi_right_single->Draw("SAME");
		  h_data_diff_proton_reco_pair_xi_left_multi->Draw("SAME");
		  h_data_diff_proton_reco_pair_xi_right_multi->Draw("SAME");
		  h_data_ratio_proton_reco_pair_xi_left_single->Draw("SAME");
		  h_data_ratio_proton_reco_pair_xi_right_single->Draw("SAME");
		  h_data_ratio_proton_reco_pair_xi_left_multi->Draw("SAME");
		  h_data_ratio_proton_reco_pair_xi_right_multi->Draw("SAME");

		  hs_mass.Write();
		  hs_pt.Write();
		  hs_y.Write();
		  //hs_n_ext_fromPV_3.Write();
		  hs_proton_xi_left_single.Write();
		  hs_proton_xi_right_single.Write();
		  hs_proton_xi_left_multi.Write();
		  hs_proton_xi_right_multi.Write();
		  hs_diff_proton_reco_pair_xi_left_single.Write();
		  hs_diff_proton_reco_pair_xi_right_single.Write();
		  hs_diff_proton_reco_pair_xi_left_multi.Write();
		  hs_diff_proton_reco_pair_xi_right_multi.Write();
		  hs_ratio_proton_reco_pair_xi_left_single.Write();
		  hs_ratio_proton_reco_pair_xi_right_single.Write();
		  hs_ratio_proton_reco_pair_xi_left_multi.Write();
		  hs_ratio_proton_reco_pair_xi_right_multi.Write();
		  hs_mass_re.Write();
		  hs_pt_re.Write();
		  hs_y_re.Write();
		  //hs_n_ext_fromPV_3_re.Write();
		  hs_proton_xi_left_single_re.Write();
		  hs_proton_xi_right_single_re.Write();
		  hs_proton_xi_left_multi_re.Write();
		  hs_proton_xi_right_multi_re.Write();
		  hs_diff_proton_reco_pair_xi_left_single_re.Write();
		  hs_diff_proton_reco_pair_xi_right_single_re.Write();
		  hs_diff_proton_reco_pair_xi_left_multi_re.Write();
		  hs_diff_proton_reco_pair_xi_right_multi_re.Write();
		  hs_ratio_proton_reco_pair_xi_left_single_re.Write();
		  hs_ratio_proton_reco_pair_xi_right_single_re.Write();
		  hs_ratio_proton_reco_pair_xi_left_multi_re.Write();
		  hs_ratio_proton_reco_pair_xi_right_multi_re.Write();
		  hs_clone_mass.Write();
		  hs_clone_pt.Write();
		  hs_clone_y.Write();

	     h_data_mass->Write();
	     h_data_pt->Write();
	     h_data_y->Write();
		  //h_data_n_ext_fromPV_3->Write();
	     h_data_proton_xi_left_single->Write();
	     h_data_proton_xi_right_single->Write();
	     h_data_proton_xi_left_multi->Write();
	     h_data_proton_xi_right_multi->Write();
	     h_data_diff_proton_reco_pair_xi_left_single->Write();
	     h_data_diff_proton_reco_pair_xi_right_single->Write();
	     h_data_diff_proton_reco_pair_xi_left_multi->Write();
	     h_data_diff_proton_reco_pair_xi_right_multi->Write();
	     h_data_ratio_proton_reco_pair_xi_left_single->Write();
	     h_data_ratio_proton_reco_pair_xi_right_single->Write();
	     h_data_ratio_proton_reco_pair_xi_left_multi->Write();
	     h_data_ratio_proton_reco_pair_xi_right_multi->Write();

		  f4->Close();
		 // }
		  return 0;
}
